### ISSUE TITLE
bunny rpc call block

### ISSUE THREAD

**Issue by ben-han-cn** [ruby-amqp/bunny#145]
When running rpc client code with link (https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/ruby/rpc_client.rb) using bunny(0.10.1), if change the code to run several times:
client   = FibonacciClient.new(ch, "rpc_queue")
1000.times do 
    puts " [x] Requesting fib(30)"
    response = client.call(30)
    puts " [.] Got #{response}"
end
the client will hang during several client call.
After debugging the source code, we found the following code may has problem:
         maybe_kill_consumer_work_pool! unless any_consumers?
the consumer isn't empty, which cause work pool isn't killed, and the consumer will blocking at work pool join.

Since cancel a consumer isn't very stable,  we change the rpc code by using mutex and
condition variable as following code:

 def initialize(ch, server_queue)
    // add the following at the end of initialize
    @m = Mutex.new
    @c = ConditionVariable.new
    that = self
    @reply_queue.subscribe do |delivery_info, properties, payload|
        that.response = payload.to_i
        that.m.synchronize{that.c.signal}
    end 
  end 

  def call(n)
    #correlation_id = self.generate_uuid

```
@x.publish(n.to_s,
  :routing_key    => @server_queue,
#  :correlation_id => correlation_id,
  :reply_to       => @reply_queue.name)

@m.synchronize{@c.wait(@m)}
response
```

  end

In this way, the client won't block anymore. But the performance of  ruby version is ten times slower than python version(https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/python/rpc_client.py) .
ruby version: 
real    0m4.323s
user    0m0.178s
sys 0m0.038s

python version:
real    0m0.399s
user    0m0.191s
sys 0m0.034s

Is there anyway to promote the performance of ruby version?

**Comment by gkirill** [comment]
All, if my understating correct that ben-han-cn's example, will only send message to the queue one by one, e.g. it will not send the next message, until the response for the previous one has being received? 

If yes, is there a way to do this more efficiently?

**Comment by michaelklishin** [comment]
The way to do it more efficiently is to not use locking. Publishing in RabbitMQ and all clients is entirely asynchronous, same with [consumer deliveries](http://www.rabbitmq.com/confirms.html) unless the user opts in. Tutorial 6 is merely an example, there is no reason why request/response has to be done that way.

**Comment by michaelklishin** [comment]
This is not a support forum, please take your future questions to the mailing list.
