### ISSUE TITLE
RabbitMQ 3.4 "fast RPC" (amq.rabbitmq.reply-to) support

### ISSUE THREAD

**Issue by chaopeng** [ruby-amqp/bunny#268]
Hi, I try to port java rpcclient to ruby, and face rpc server cannot receive message if publish opts has :reply_to=>'amq.rabbitmq.reply-to', but in java client is ok and will automatic add some uniform info, rpc server will receive something like that reply_to = amq.rabbitmq.reply-to.g2dkABNyYWJiaXRAY2hhby13b3JrLXBjAAAFFQAAAAAD.AJ3VTrgqUFg23rPZHofGqw==

**Comment by michaelklishin** [comment]
So I'm not sure what we can support here (as long as we don't provide a request/reply implementation). [The docs](http://www.rabbitmq.com/direct-reply-to.html) are not super detailed but there is nothing on the Bunny end that may need changing.

**Comment by cognitiveflux** [comment]
@michaelklishin Just tested with `Bunny` 2.1.0 and RabbitMQ 3.5.4 and fast RPC support works fine without any changes.  If anyone runs into issues, it's likely because they didn't create the consumer to handle the RPC reply from the server _before_ sending the RPC message from the client.
