### ISSUE TITLE
I/O timeouts with 1.6.3 but seemingly not 1.3.1

### ISSUE THREAD

**Issue by maximchick** [ruby-amqp/bunny#277]
Hi, 

After upgrading bunny gem from 1.3.1 to 1.6.3 I started getting following error from both producers and consumers:
```
E, [2015-01-22T13:25:31.449598 #25957] ERROR -- #<Bunny::Session:81761700 guest@127.0.0.1:5672, vhost=/, hosts=[127.0.0.1]>: Got an exception when receiving data: IO timeout when reading 7 bytes (Timeout::Error)
W, [2015-01-22T13:25:31.449730 #25957]  WARN -- #<Bunny::Session:81761700 guest@127.0.0.1:5672, vhost=/, hosts=[127.0.0.1]>: Recovering from a network failure...
/home/chechel/.rvm/gems/ruby-1.9.3-p448/gems/bunny-1.6.3/lib/bunny/session.rb:870:in `send_frame': Trying to send frame through a closed connection. Frame is #<AMQ::Protocol::MethodFrame:0x9c044ec @payload="\x00(\x00\n\x00\x00\nbroadcast2\x06fanout\x00\x00\x00\x00\x00", @channel=1>, method class is AMQ::Protocol::Exchange::Declare (Bunny::ConnectionClosedError)
	from /home/chechel/.rvm/gems/ruby-1.9.3-p448/gems/bunny-1.6.3/lib/bunny/channel.rb:1134:in `exchange_declare'
	from /home/chechel/.rvm/gems/ruby-1.9.3-p448/gems/bunny-1.6.3/lib/bunny/exchange.rb:245:in `declare!'
	from /home/chechel/.rvm/gems/ruby-1.9.3-p448/gems/bunny-1.6.3/lib/bunny/exchange.rb:83:in `initialize'
	from /home/chechel/.rvm/gems/ruby-1.9.3-p448/gems/bunny-1.6.3/lib/bunny/channel.rb:298:in `new'
	from /home/chechel/.rvm/gems/ruby-1.9.3-p448/gems/bunny-1.6.3/lib/bunny/channel.rb:298:in `fanout'
	from fanout/producer.rb:9:in `<main>'
```

rabbitmq-server restart doesn't help, rollback to 1.3.1 helps

**Comment by michaelklishin** [comment]
We need at least a code snippet to investigate. Are you sure you aren't observing a network connectivity issue followed by a publish on a closed connection? (as in, the problem is not really version-specific).

If it is, there should be a way to reproduce it reasonably easy. Also, you are not specifying the OS.

**Comment by maximchick** [comment]
```
uname -a
Linux mc 3.2.0-74-generic-pae #109-Ubuntu SMP Tue Dec 9 17:00:00 UTC 2014 i686 i686 i386 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

Producer code snippet:
```
require "bunny"

conn = Bunny.new
conn.start

ch       = conn.create_channel
x        = ch.direct("scoring", durable: true)
routing_key = ARGV.shift

x.publish(msg, routing_key: routing_key, persistent: true)
puts " [x] Sent '#{msg}'"

conn.close
```

**Comment by michaelklishin** [comment]
Please try with master (or a different `connect_timeout` value), I suspect this may be due to Bunny's timeout being lower than certain OS-level ones (e.g. DNS resolution).

The provided snippet is pretty trivial and doesn't time out in multiple environments, including CI.

**Comment by drewish** [comment]
I'm also running into this on OS X with rabbitmq 3.4.4. Frustratingly my coworkers are running the same code and having no issues.

**Comment by michaelklishin** [comment]
I've seen timeouts on OS X recently in stress tests that involved tens of thousands of connections. While on Linux you quickly get a sensible failures to open a socket, OS X seems to simply time out some of the time. So check your OS-wide file handles limit.

**Comment by drewish** [comment]
I haven't tracked it down but my issue comes up only when I'm using the new version of bunny and on a VPN. It seems a little crazy to me sense to me since I'm connecting to localhost. Now that I know what triggers it I'm able to work around it. I'll try to do some more digging into it later on.

**Comment by michaelklishin** [comment]
VPN almost certainly changes your DNS server configuration. JFYI.

**Comment by drewish** [comment]
Yeah definitely would affect that, but my understanding was that `localhost` would be resolved by `/etc/hosts`. I'm not clear what changed in bunny that would be affected by it.

**Comment by michaelklishin** [comment]
It should be. However, at least in theory, the following may be happening:

 * Try resolving using primary DNS server
 * Then secondary
 * Then /etc/hosts

(I'm speculating)
