### ISSUE TITLE
Move to RSpec 3.1

### ISSUE THREAD

**Issue by michaelklishin** [ruby-amqp/bunny#279]

**Comment by michaelklishin** [comment]
This is pretty much about updating matchers but unless Transpec works flawlessly, can be quite time consuming. See https://github.com/ruby-amqp/march_hare/pull/71.

**Comment by michaelklishin** [comment]
@foeken would you be so kind to look into this? In case you have interest in contributing more to Bunny, this is a good starting point :)

Most of my time these days is spent on RabbitMQ and a couple of other clients.

**Comment by bartj3** [comment]
I don't know if @foeken is still planning on picking this up but if not I wouldn't mind giving it a go this weekend?

**Comment by michaelklishin** [comment]
@bartj3 that would be fantastic, thank you!

**Comment by bartj3** [comment]
Transpec managed to get most of it correctly, I'm running into some problems with `spec/higher_level_api/integration/tls_connection_spec.rb` though, the syntax should be properly updated but I can't get the spec green (before the update) so I can't make sure I didn't break something.

I'll look into the last spec later and once everything is rebased into a nice commit I'll open a pull request.

**Comment by michaelklishin** [comment]
Are you aware of [tls-gen](https://github.com/michaelklishin/tls-gen/)?

**Comment by michaelklishin** [comment]
Yeah, don't worry about TLS connection tests, I can update them if needed.
