### ISSUE TITLE
Verify peer is set to nil by default, this should default to true

### ISSUE THREAD

**Issue by foeken** [ruby-amqp/bunny#280]
The docs say this defaults to true (comments on the session.rb options) but it actually is not set. So even if you add all the certificates and enable TLS, it still uses VERIFY_NONE and skips the post_connection_check on the SSLSocket.

**Comment by michaelklishin** [comment]
I'm not sure we want it to be `true` by default. It makes sense in general but in development this would be an annoyance and major support pain point.

**Comment by foeken** [comment]
But now this caused us to skip verification of certificates in production for several months...

It would make sense that *if* you enable TLS, you also want verify_peer by default (this is how the newer languages like Go handle SSL settings)

**Comment by michaelklishin** [comment]
Go is not a significant enough argument but I believe most HTTP clients do the same. Let me see how much updating the specs may need. This certainly will cause a lot of pain because most developers don't have much clue about TLS :(

**Comment by michaelklishin** [comment]
So this means "using tls-gen certificates on localhost not going to work by default". I suspect that the doc guides would need a fair share of updating to disable peer verification by default with a visible comment saying "please enable this in production".

**Comment by foeken** [comment]
TLS is a beast to get right. My issue is mostly with the silent agreement to the disabling. it's fine to disable it by default, but then a warning could be displayed on runtime and the docs should state it clearly :)

**Comment by michaelklishin** [comment]
#281

**Comment by michaelklishin** [comment]
@foeken I added you as a collaborator. Feel free to merge #281 if you like it :)

**Comment by foeken** [comment]
Oee cool :) tnx :)

**Comment by foeken** [comment]
Seems I can't click merge, maybe the collab setting did not stick?

**Comment by foeken** [comment]
Ahh stupid. There is an e-mail confirm now. I merged it!

**Comment by michaelklishin** [comment]
Well, now we need to update the doc examples to do basically what `tls_spec.rb` now does, with a comment :(
