### ISSUE TITLE
Cannot specify ports when specifying multiple hosts

### ISSUE THREAD

**Issue by phaneesh** [ruby-amqp/bunny#282]
Not able to specify different ports when using multiple hosts. If we are hosting multiple RMQ instances on same node (different tenants); then we will not be able to run RMQ on the same port. Please provide a option to specify multiple ports when specifying multiple hosts.

**Comment by michaelklishin** [comment]
Feel free to submit a pull request, it's not an intricate change ;)

**Comment by bartj3** [comment]
I would like to take a stab at this if thats ok with you @phaneesh?

The thing is that I'm not sure how this would look in the connection options, it would be dirty to just specify the port in the hosts array. Does anyone have an idea what the parameters would look like?

**Comment by michaelklishin** [comment]
@bartj3 in the Java client, this is called "addresses", and each "address" can be a pair. If both addresses and hosts are specified, the client should raise an argument error saying they are mutually exclusive.

**Comment by bartj3** [comment]
first attempt is at https://github.com/bartj3/bunny/commit/82664629936a9b5b6d1c4f246d07872700227577, I'm far from happy with the result, but the specs are green so now I'm going to try to refactored this into something usable and readable.

**Comment by michaelklishin** [comment]
@bartj3 looks like a promising start, thank you! Please add a test case that tries to use both `:hosts` and `:addresses`.

**Comment by bartj3** [comment]
I added two testcases and the required validations:
Both `:hosts` and `:address` are invalid,
But a single host combined with an array of hosts/addresses raises an error as well, before the host was silently ignored.

I'm not sure if raising an error in the last case is the correct way to go here, if people are already doing this an upgrade of Bunny will start throwing exceptions.

Another thing I noticed is that the addresses now use the host shuffle strategy, which is a bit counterintuitive. The best way to solve this would to add a `shuffle_strategy` and to maybe deprecate `hosts_shuffle_strategy` later on.

A different solution would be to make hosts & addresses one array parameter with one strategy. `hosts` would become an alias of `addresses`, and the `addresses_from` would then check each item in the array to see if it's a host or address, and append a port if it's a host.

The complete diff of the feature so far is at: https://github.com/ruby-amqp/bunny/compare/master...bartj3:feature/addresses

**Comment by michaelklishin** [comment]
@bartj3 yes, we should log a warning but not throw an exception.

I like the idea of unifying hosts and addresses.

**Comment by bartj3** [comment]
I've changed the raise into a warn and combined the hosts and addresses. I don't have time to refactor this weekend but I'll continue with this next week.

**Comment by michaelklishin** [comment]
@bartj3 thank you!

**Comment by bartj3** [comment]
the refactor shouldn't take this long, sorry for the delay! I have time to work on this tomorrow

**Comment by michaelklishin** [comment]
@bartj3 sounds good!

**Comment by bartj3** [comment]
The refactored and rebased branch is at https://github.com/ruby-amqp/bunny/compare/master...bartj3:feature/addresses, I'm still not very happy with the `addresses_from` function but not sure how to clean it up further. Feedback is welcome!

**Comment by michaelklishin** [comment]
@bartj3 thank you!

@priviterag so the primary thing to do here is to QA it.

**Comment by priviterag** [comment]
@michaelklishin @bartj3  :+1: thanks!
