### ISSUE TITLE
Exception in subscribe

### ISSUE THREAD

**Issue by nateless** [ruby-amqp/bunny#284]
Got an exception, full detail about our app is here: #283. I basically opened a lot of tabs and it crashed.

```
/Users/nateless/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bunny-1.7.0/lib/bunny/channel.rb:920:in `basic_consume_with': undefined method `consumer_tag' for #<AMQ::Protocol::Queue::BindOk:0x007fa52d141f48> (NoMethodError)
	from /Users/nateless/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bunny-1.7.0/lib/bunny/queue.rb:184:in `subscribe'
	from /Users/nateless/Ruby/service/app/controllers/stream_controller.rb:19:in `block (2 levels) in index'
```

Line 19: `$channel.queue(global_service.user.id.to_s).bind(x).subscribe do |delivery_info, metadata, data|`
```Ruby
			rabbit = Thread.new do
				Thread.current.abort_on_exception = true
				x   = $channel.fanout("stats")

				$channel.queue(global_service.user.id.to_s).bind(x).subscribe do |delivery_info, metadata, data|
					reply(tubesock, data)
				end
				ap x.methods
			end
```

Also killing rabbit thread leaks consumers. I suppose I need to call create_channel and close it with killing the thread?

**Comment by michaelklishin** [comment]
@nateless I thought I've made it pretty clear in #283 (and in our docs) that channels **must not be shared between threads**. Connections can be in most cases but channels never can.

**Comment by nateless** [comment]
Sorry, forgot to update the code.

I do create channel for each thread, then kill the thread and close that channel, however on next page refresh I receive `raise_if_continuation_resulted_in_a_connection_error!': Connection-level error: CHANNEL_ERROR - expected 'channel.open' (Bunny::ChannelError)`.

If I don't close the channel, it leaks channels.

**Comment by michaelklishin** [comment]
That means that you are trying to use a channel number that isn't open. I can't suggest much knowing only that it happens "on the next page". There are tests in Bunny's suite that concurrently open and close hundreds of connections.

Use our [Tracer tool](http://rabbitmq.com/java-tools.html) or Wireshark 1.99.x to see what's going up and down the wire, or simply use a new connection per client/page/whatever. It's not very efficient but doesn't get safer than that.
