### ISSUE TITLE
default_channel?

### ISSUE THREAD

**Issue by shtirlic** [ruby-amqp/bunny#290]
Updated from 1.4 to 1.7 and got this, any ideas?
`connect': undefined method `default_channel' for #<Bunny::Session:0x007fa487943da0> (NoMethodError)

**Comment by shtirlic** [comment]
Found commit https://github.com/ruby-amqp/bunny/commit/7682f2d6116c37e2056034ad1f676006b82aef67#diff-f89bb2431c20be4ed2b0a5b3bfa4cf8e

Nothing in changelog about breaking API

**Comment by michaelklishin** [comment]
`Bunny:Session#default_channel` was a 0.8 relict that "helped users" by hiding channels in the API.

We have been dragging it along for many versions. Please open channels explicitly now.

**Comment by shtirlic** [comment]
It's ok, but why there is no mention in change log. I think that API breaking changes should be mentioned at least in change log.

**Comment by michaelklishin** [comment]
Because I genuinely expected that by now exactly 0 people use Bunny the same way they did before 0.9.

**Comment by shtirlic** [comment]
@michaelklishin ;) ok, I made poll request with updates https://github.com/ruby-amqp/bunny/pull/291

**Comment by michaelklishin** [comment]
The commit that removed it is 7682f2d6116c37e2056034ad1f676006b82aef67.
