### ISSUE TITLE
One consumer get multiple messages from queue

### ISSUE THREAD

**Issue by ozeron** [ruby-amqp/bunny#292]
I want to get multiple messages from queue. Make calculation on them and ack last one. If this is possible with bunny? I read tutorials and guides and don't found workaround how to perform this. Can you help me?

My code looks like this:
```
q = channel.queue(name, auto_delete: false, durable: true)
    q.subscribe(subscribe_options) do |delivery_info, properties, payload|
      # receive N messages in payload and do some work
      DataUpdater.parse_data_and_update_db(payload, name)
      # ack last message
      channel.ack(delivery_info.last.delivery_tag, true)
    end
```

**Comment by michaelklishin** [comment]
You can ack multiple messages at once, that's what the "multiple" argument is for in `Bunny::Channel#ack` and similar. Delivery tag then specifies up to which delivery tag you are acking (so, the last one, just as you want).

**Comment by ozeron** [comment]
@michaelklishin Yes, I now how to ack multiple messages but how to get multiple messages at once. As I understand subscribe return one message from queue in payload, what if I want to receive 10 messages?

**Comment by michaelklishin** [comment]
You can either use `basic.get` (just call it N times with manual acknowledgements set to true) or set your channel's prefetch value to N and add a consumer. This is documented quite well for both Bunny and RabbitMQ in general (in the tutorials).

**Comment by michaelklishin** [comment]
for the love of all that is good, do not use `alias_method_chain` or any of that crazy Rails magic. We will not even consider looking at bug reports that involve monkey-patching of Bunny.
