### ISSUE TITLE
Unexpected log behaviour due to settting of @logger.progname

### ISSUE THREAD

**Issue by bodymindarts** [ruby-amqp/bunny#296]
Hello,

there was unexpected log output after passing `Rails.logger` to Bunny via ```Bunny.new(logger: Rails.logger)```.

The reason was that Bunny sets `@logger.progname = to_s if @logger.respond_to?(:progname)` [here](  
https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L1112).

Would it be possible to delete [this line](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L1112) so that Bunny doesn't change the behaviour of the logger once it gets [passed in](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L150)?

Even in the case that Bunny defines its [own logger](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L1165) I don't see the reason to reassign the attribute since I don't see how it could have changed since the `@logger` was first set.

If deleting the line is not an option. How are other people dealing with this?

**Comment by michaelklishin** [comment]
@bodymindarts we'd need to do some code archeology to find out why it was added. I'm in favour of making it easier to use Rails-provided loggers. Feel free to investigate and submit a PR :)

**Comment by bodymindarts** [comment]
I see now the `Session#to_s` [method](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L941) will change when `@transport` is [reassigned](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L1109) because `host` [depends on it](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L226). So it makes sense if the logger was defined in Bunny to stay consistent.
I think reassignment should however be skipped if the logger was passed in from the outside so that its behaviour doesn't change.

**Comment by michaelklishin** [comment]
@bodymindarts thank you. Feel free to update ChangeLog.md. You can also backport this to the stable branch (`1.7.x-stable`) as needed and submit another PR.
