### ISSUE TITLE
Publish sometimes leaks messages

### ISSUE THREAD

**Issue by BirknerAlex** [ruby-amqp/bunny#300]
Hello,

I'm running a rails application together with puma with multiple workers and threads. The RabbitMQ (version 3.5.1) cluster has currently 3 nodes, all queues are replicated to all nodes. The cluster is load balanced by haproxy.

Sometimes (~ 5% of requests) on high loads it happens that publish doesn't sends a message to the RabbitMQ target queue. Without error message or exception.

Code which is used:

```ruby

@rabbitmq ||= Bunny.new(
    :host => RABBITMQ_CONFIG['events']['hostname'],
    :port => RABBITMQ_CONFIG['events']['port'],
    :user => RABBITMQ_CONFIG['events']['username'],
    :pass => RABBITMQ_CONFIG['events']['password'],
    :vhost => RABBITMQ_CONFIG['events']['vhost'],
    :automatically_recover => false
)
@rabbitmq.start

c = @rabbitmq.create_channel
x = c.default_exchange
q = c.queue("events_#{event.target_host}", auto_delete: false, durable: true)

x.on_return do |return_info, properties, content|
    raise "Event can't be delivered: #{return_info.to_s}"
end

x.publish(XYZ, :routing_key => q.name, :mandatory => true)

# more code ....
```

The Bunny connection and sending code is inside a Singleton class. So there is only one connection per puma worker.

Publish raises no exception or something like that but it doesn't puts an message into the target queue. It also doesn't returns the message back to the publisher.

It also happens on high loads, if I send only a few messages / minute there is no problem. I think it can be a timing problem. Maybe its too much for one connection per worker process? But I am still missing the error message.Has anyone an idea how I can debug this on a better way? 

Best regards,
Alexander

**Comment by michaelklishin** [comment]
>The Bunny connection and sending code is inside a Singleton class.
> So there is only one connection per puma worker.

I'm pretty sure that means "I'm sharing a connection between threads". Which should be fine. But at least in your code example you also have one channel: which is not supported and [documented as such](http://rubybunny.info/articles/concurrency.html).

A good way to investigate is to use Wireshark and filter by

```
tcp.port == 5672 and amqp
```

to only see AMQP 0-9-1 methods.
