### ISSUE TITLE
Expiration time in message properties is not converted to Time

### ISSUE THREAD

**Issue by wconrad** [ruby-amqp/bunny#301]
With Bunny 1.7.0, when reading a message using Queue#pop, the `timestamp` property is a Time:

    delivery_info, properties, content = @queue.pop
    p properties.timestamp.class     # => Time
    p properties.timestamp           # => 2015-01-01 12:00:00 -0700

However, the `expiration` property is a String:

    p properties.expiration.class    # => String
    p properties.expiration          # => "1420138801"

This is consistent with the documentation for Bunny::MessageProperties:

    # @return [String] Message expiration, as set by the publisher
    def expiration
      @properties[:expiration]
    end

But it's a little surprising.  It would be nice if `expiration` were also converted to a Time.

# Breaking, or non-breaking fix?

'There are two obvious ways to address this.

* Change the type of `expiration` from _String_ to _Time_.  This would be a breaking API change.

* Add a new field, `expiration_time`, type _Time_.  This is a non-breaking API change.  One might decide to deprecate `expiration`, or just leave it be.

# The amq-protocol gem might be involved

It is the amq-protocol gem that does the conversion for _timestamp_; it seems that it could be the proper place to convert `expiration` as well.  As with `bunny`, this would be a breaking change for `amq-protocol`.

**Comment by michaelklishin** [comment]
Expiration is not semantically an absolute time, so `TableValueDecoder` should be changed to return a string. Then we can bump `amq-protocol` version to `1.10`. Feel free to file an issue there and take a look.

**Comment by wconrad** [comment]
My mistake: I didn't realize that expiration represents an interval.  Thanks.

**Comment by michaelklishin** [comment]
No worries. `git blame` suggests relevant `TableValueDecoder` lines were changed in July 2011. It wasn't a very bright idea and we should fix it.
