### ISSUE TITLE
I'm having too many blocked connections

### ISSUE THREAD

**Issue by Davidslv** [ruby-amqp/bunny#302]
Hey guys,

I'm new into using RabbitMQ, we are using bunny but our connections are being blocked, at the moment I have **608** connections blocked. We also have a connection pool as follows:

```ruby
$amqp_connection_pool = ConnectionPool.new(size:25), timeout: 5) do
  connection = Bunny.new ENV['AMQP_URL'] || 'amqp://127.0.0.1:5672'
  connection.start
  connection.create_channel
end
```
I was told that we somehow are having too many connections, that should be around 2-5.

My question is if there's a way on bunny to know that a connection is blocked and if it is then disconnect, I'm not sure, maybe you can show me the right direction, this is how one of the connections is looking at the moment:

![screen_shot_2015-05-08_at_15_48_54](https://cloud.githubusercontent.com/assets/136777/7538808/9536d574-f59a-11e4-8e7a-2e9a1a6c517c.png)

Thank you for your help

**Comment by michaelklishin** [comment]
We have a mailing list for questions.

You may want to get familiar with [resource-drive alarms](http://www.rabbitmq.com/alarms.html) and check RabbitMQ server logs to see why you get blocked connections. It is certainly not the number of sockets used, that prevents new connections from being accepted. The overview tab also highlights alarms in red.

Connections have [on_blocked and on_unblocked](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L397-415) that are invoked when an alarm goes off.
