### ISSUE TITLE
activemq

### ISSUE THREAD

**Issue by ploef** [ruby-amqp/bunny#304]
Hi,

Do you have any idea if bunny can also connect with ActiveMQ (5.9.1)? 
I have enabled AMQP on ActiveMQ but keep getting errors connecting.

(frame.rb:60:in `decode_header': Empty response received from the server. (AMQ::Protocol::EmptyResponseError))

Kind regards,
Peter

**Comment by michaelklishin** [comment]
Bunny is an AMQP 0-9-1 client focused on RabbitMQ.
