### ISSUE TITLE
Timeout Exception when having custom publish timeout of 500ms

### ISSUE THREAD

**Issue by ranjith-mrk** [ruby-amqp/bunny#305]
Hello,

App Environment:

    Rails 3.2
    Ruby 2.1.5
    Passenger(http://rubybunny.info/articles/connecting.html#using_bunny_with_passenger)
    Rabbitmq Config :
       host: <host>
       port: <port>
       username:<username>
       password: <password>
       threaded: false
       heartbeat: 30
       automatic_recovery: true
       recover_from_connection_close: true

A Timeout block of 0.5 seconds encloses the publisher code. When the load on the server increases, I am getting a timeout error with the following exception. 

    /usr/local/lib/ruby/2.1.0/monitor.rb: 185:in `lock'
    /usr/local/lib/ruby/2.1.0/monitor.rb: 185:in `mon_enter'
    /usr/local/lib/ruby/2.1.0/monitor.rb: 209:in
    `mon_synchronize'
    …ems/ruby/2.1.0/gems/bunny-1.7.0/lib/bunny/transport.rb: 158:in
    `write_without_timeout'
    …_gems/ruby/2.1.0/gems/bunny-1.7.0/lib/bunny/session.rb: 886:in
    `send_frame_without_timeout'
    …_gems/ruby/2.1.0/gems/bunny-1.7.0/lib/bunny/session.rb: 921:in `block
    (2 levels) in send_frameset_without_timeout'
    …_gems/ruby/2.1.0/gems/bunny-1.7.0/lib/bunny/session.rb: 921:in `each'
    …_gems/ruby/2.1.0/gems/bunny-1.7.0/lib/bunny/session.rb: 921:in `block
    in send_frameset_without_timeout'
                       /usr/local/lib/ruby/2.1.0/monitor.rb: 211:in
    `mon_synchronize'
    …_gems/ruby/2.1.0/gems/bunny-1.7.0/lib/bunny/channel.rb:1415:in `synchronize'
    …_gems/ruby/2.1.0/gems/bunny-1.7.0/lib/bunny/session.rb: 920:in
    `send_frameset_without_timeout'
    …_gems/ruby/2.1.0/gems/bunny-1.7.0/lib/bunny/channel.rb: 565:in `basic_publish'
    …gems/ruby/2.1.0/gems/bunny-1.7.0/lib/bunny/exchange.rb: 137:in `publish'

Is it expected for the publisher to take more than 0.5s? If not what is the ideal publish timeout? Is there any client configuration that can speedup the publish operation?

**Comment by michaelklishin** [comment]
It can be way more than 0.5s if your publisher gets blocked due to resource alarm (about which there will be entries in the RabbitMQ log). Make sure you register [a connection.blocked](https://www.rabbitmq.com/connection-blocked.html) notification handler.

5-10 seconds is a value I'd use.
