### ISSUE TITLE
require 'bunny' uses more memory than require 'rails/all'

### ISSUE THREAD

**Issue by salimane** [ruby-amqp/bunny#306]
Requiring the gem ``bunny`` uses more memory than require ``rails/all``. It uses ``23MB`` while in comparison ``rails/all`` uses ``17MB``.

```shell
bunny: 23.9688 MiB
rails/all: 17.6445 MiB
elasticsearch/model: 2.0195 MiB
mysql2: 0.6011 MiB
```

To reproduce this :
- Put this in your gemfile:
```ruby
gem 'rails', '3.2.21'
gem 'bunny', '~> 1.7.0'
gem 'elasticsearch-rails', '~> 0.1.7', require: ['elasticsearch/model']
gem 'elasticsearch-model', '~> 0.1.7'
gem 'elasticsearch', '~> 1.0.8'
gem 'mysql2', '~> 0.3.18'
gem 'derailed', group: :development
gem "stackprof", group: :development
```
- Then run 
```shell
bundle install
RAILS_ENV=production rails console # to check if you can run your app with prod env
RAILS_ENV=production rails server # to run your app with prod env
RAILS_ENV=production rake assets:precompile # sometimes this is needed
tail -f logs/production.log # to check errors in logs...
derailed exec perf:mem # check memory usage by gems
```

May be we could check how we could reduce the memory usage.
Thanks

**Comment by carlhoerberg** [comment]
i don't know "derailed" calculate memory usage but just looking at "ps aux" then:

irb <-- 15mb
irb -r bunny <-- 17mb
irb -r sinatra <-- 19mb

so i don't think bunny uses particularly much memory. (ruby 2.2.1, os x)

**Comment by salimane** [comment]
here is @schneems https://github.com/schneems/derailed_benchmarks . May be @schneems can chime in :)

**Comment by schneems** [comment]
@carlhoerberg all it does is run `ps` before and after each require in your project. Using `get_process_mem` gem.

I added this to a gemfile:

```ruby
source "https://rubygems.org"

gem 'bunny', '~> 1.7.0'
gem 'derailed'
gem "thor"

gem "rails"
```

Then I ran `$ derailed bundle:mem` and it doesn't look like bunny is using much memory

```
  bunny: 1.2656 mb
    bunny/session: 0.4805 mb
    amq/protocol/client: 0.4336 mb
```

Maybe it's one specific version of bunny? In my gemfile.lock

```
    bunny (1.7.0)
      amq-protocol (>= 1.9.2)
```

**Comment by michaelklishin** [comment]
This is not a particularly indicative benchmark. Try referencing ActiveRecord::Base and other key Rails classes, they are all likely lazy loaded.

**Comment by michaelklishin** [comment]
I doubt we can significantly reduce memory usage in Bunny: it is a pretty small library that relies on another small library, all eagerly loaded. Try eagerly load Rails to compare.

**Comment by schneems** [comment]
>  I absolutely fail to believe that modern Rails versions use only ~ 20 MB of RAM.

This is RAM on boot, not ram while running. I.e. we're looking at objects generated and retained as well as RubyVM instructions that take up memory. We're not looking at running memory, only memory at Require time. In my experience this number is around 60mb for a medium sized Rails app. Note that by only putting "rails" in this micro benchmark, we're not requiring other libraries like sprockets/nokogiri/mail/etc.

> This is not a particularly indicative benchmark.

It indicates exactly how much memory your app is using when it requires files from a Gemfile. Like all benchmarks, it's very specific. If you want to make sure all those things are required you can run `$ derailed exec perf:mem` will actually load up your app. When I tried this using the Gemfile that was mentioned at the beginning I get these results:

```
TOP: 31.8086 mb
  application: 9.1602 mb
    rails/all: 2.6094 mb
      active_record/railtie: 2.5195 mb
        active_record: 1.8438 mb
          arel: 0.9727 mb
            arel/nodes: 0.3828 mb
            arel/visitors: 0.3125 mb
        action_controller/railtie: 0.668 mb
          action_controller: 0.5859 mb
            abstract_controller: 0.3125 mb
    bunny: 1.293 mb
      amq/protocol/client: 0.4609 mb
      bunny/session: 0.4063 mb
  /private/tmp/bunny-problem/app/controllers/application_controller: 8.5938 mb
    action_view/base: 4.6563 mb
      action_view/helpers/form_tag_helper: 0.6953 mb
      action_view/template: 0.3672 mb
  rails: 5.0313 mb
    rails/application: 2.707 mb
      rails/plugin: 2.4688 mb
        rails/engine: 2.2695 mb
          rails/railtie: 1.9102 mb
            rails/configuration: 1.543 mb
              active_support/ordered_options: 1.3906 mb
                active_support/ordered_hash: 1.3555 mb
                  psych: 1.2227 mb
                    psych/nodes: 0.4961 mb
                      psych/nodes/node: 0.3047 mb
                    psych/visitors: 0.3867 mb
    active_support/core_ext/logger: 1.0391 mb
      active_support/deprecation: 0.5352 mb
      logger: 0.3477 mb
    active_support: 0.6992 mb
      active_support/dependencies/autoload: 0.5039 mb
        active_support/inflector/methods: 0.4258 mb
  tzinfo: 0.5 mb
  rack/lint: 0.3398 mb
```

I couldn't reproduce the behavior that @salimane is seeing. If anyone else can take a crack at it, or if I can get some more info I can figure out why you're seeing those results.

**Comment by michaelklishin** [comment]
So you compare an eagerly loading library with a lazily loading one, only care about "require time" and find that somehow useful?

I fail to see how it may be. Feel free to profile Bunny and suggest improvements but this whole benchmark is of no real value if you ask me.

**Comment by schneems** [comment]
> this whole benchmark is of no real value if you ask me.

This benchmark is solely responsible for shaving 36% of the boot memory footprint of Rails apps http://www.schneems.com/2014/11/07/i-ram-what-i-ram.html. 

Here's some background reading material about retained versus allocated memory and why keeping both small is important: http://www.sitepoint.com/ruby-uses-memory/

Or if you're an audio/visual learner, here's similar info my talk at RailsConf in video format http://www.schneems.com/2015/05/11/how-ruby-uses-memory.html you can skip forwards about 10-20 minutes to get into the meat of the memory behavior and measurement.

Feel free to ping me with questions

I understand you're doing this for free, in your free time, but so are we. We're trying to be helpful and have  a conversation here. You're coming off a bit combative, and I can't tell which of your questions are facetious. I'm happy to provide details if you need them. Currently I am seeing that this benchmark is supporting what you're saying, that bunny is a small library. If you disagree with my conclusions (which it sounds like you're doing when you're referring to this benchmark as useless) feel free to suggest a different benchmark or measuring mechanism. I'll happily try to reproduce your results, I love being exposed to new tools and techniques.

Thank you to @salimane for running benchmarks and reporting. Even if my results don't agree with yours, it's great to have a second set of eyes for repro. I don't think @michaelklishin is interested in the conversation about why you're getting different results than me. Maybe a more appropriate place would be to open an issue on github.com/schneems/derailed_benchmarks. Also try running with the environment variable `RUBY_GC_HEAP_GROWTH_FACTOR=1.05` you may be hitting a memory "cliff" where Ruby's GC allocates lots of memory (up to 1.8x I believe in some Ruby versions) even though the library only needs 1.4mb when it is required. That or you may be running into a bug with my lib.

**Comment by michaelklishin** [comment]
@schneems sorry if sound like a dick. I'm all for profiling Bunny. Yes, I'm well aware of MRI's memory allocator behaviour. However, measuring "require time" RAM use is only valuable if your application never does anything beyond loading code. So no, this benchmark does not concern me one bit. Bunny is a very small library compared to Rails, Rails by no means uses just ~ 20 MB in real world scenarios.

**Comment by schneems** [comment]
You're correct Rails doesn't use 20MiB of memory in the wild. What this benchmark is saying is that 20MiB is the the lowest realistic value it could possibly use. Another way to think about it, is It's the the baseline from which memory use will only go up. Requiring the gem takes 20MiB of memory, using it will only result in more. What we're looking for is a dependency that uses a larger than normal amount of RAM at the start. So if I was able to reproduce the results originally reported we would need to see why the base line for bunny is so large (though it's not). You can see this elevated baseline in some libraries like `mime-types` or `fog`. It's not a perfect indicator of running memory, but we can use it to identify hotspot libraries and dig in more with other tools.

If you're looking for where runtime memory is coming from `$ derailed exec perf:objects` is a better benchmark. It tracks object allocations using `memory_profiler` rather than memory per require. If you want to see the way your app performs under load you can use `$ derailed exec perf:ram_over_time` which will show you not just your baseline, but how your ram grows as your application serves requests.

**Comment by salimane** [comment]
@schneems, I would try ``RUBY_GC_HEAP_GROWTH_FACTOR`` and really come up with solid reproduction instructions. I will probably create an issue on ``derailed_benchmarks``.
@michaelklishin, you're probably right that bunny is not the problem but somehow, something is causing ``derailed_benchmarks`` to report such memory usages. May be it's a bug with ``derailed_benchmarks``, but it's probably towards a bad code in the real app or another gem.
Thanks
