### ISSUE TITLE
Unacked messages sometimes appear

### ISSUE THREAD

**Issue by IluhaAndr** [ruby-amqp/bunny#311]
Hi! Here is a duplicate of stackoverflow question (http://stackoverflow.com/questions/30568783/rabbitmq-bunny-unacked-messages). I guess it may be useful here too.(My configuration is rails 4.1.5, bunny 1.3.1, ruby 2.1.2, rabbitmq 3.4.2)

I want to start some consumers simultaneously in different threads. Here is rake task that starts consumers:

    namespace :messaging do
    
      desc 'Start consumers'
      task start: :environment do
    
        queues = { 'app.queue1' => 4, 'app.queue2' => 10, 'app.queue3' => 50 } # etc
    
        puts "Starts #{queues.size} consumers"
    
        threads = queues.map do |name, threads_number|
          Thread.new do
            Messaging::Consumer.new(MESSAGING_CONFIG, threads_number).subscribe name
          end
        end
    
        threads.each(&:join)
    
      end
    
    end

And `Messaging::Consumer` class (slightly simplified version):

    class Messaging::Consumer
    
      TIMEOUT = 120 # 2 minutes
    
      def initialize options = {}, threads_number = 1
        @options = options || {}
        @threads_number = (threads_number || 1).to_i
      end
     
      def subscribe queue_name
        queue = queue queue_name
        puts "#{queue_name} connected"
        queue.subscribe(manual_ack: true, block: true) do |delivery_info, properties, body|
          begin
            message = JSON.parse(body).with_indifferent_access
            ActiveRecord::Base.connection_pool.with_connection do
              Timeout::timeout(TIMEOUT) do
                # somehow process message
              end
            end
          rescue Exception => e
            # retry message manually through retry exchange here
          ensure
            channel.ack delivery_info.delivery_tag
          end
        end
      end

      private
    
      def connection
        @connection ||= begin
          conn = Bunny.new @options.merge(automatically_recover: true,
                                          recover_from_connection_close: true)
          at_exit do
            self.close_connection
          end
          conn.start
          conn
        end
      end
    
      def close_connection
        @channel.try(:close) unless @channel.try(:closed?)
        @connection.try(:close) unless @connection.try(:closed?)
        puts "closed connection"
      ensure
        @connection, @channel, @queues = nil, nil, {}
      end
    
      def channel
        @channel ||= begin
          ch = connection.create_channel nil, @threads_number
          ch.prefetch @threads_number
          ch
        end
      end
    
      def queue name, exchange = nil, arguments = {}
        @queues ||= {}
        @queues[name] ||= begin
          q = channel.queue name, arguments.merge(durable: true, auto_delete: false)
          q.bind (exchange || default_exchange), routing_key: name
          q
        end
      end
    
      def default_exchange
        @default_exchange ||= create_exchange MAIN_EXCHANGE
      end
    
      def create_exchange name
        channel.direct name, durable: true
      end
    
    end

**First problem:**: when `messaging:start` is executed it doesn't necessarily start consumers for each queue (e.g. 2 of 9; it means doesn't  `puts "#{queue_name} connected"` 9 times). It happens sometimes. I guess it may be connected with rails loading classes which i see are not thread-safe (btw Messaging::Consumer is in app/services directory, eager_load = true)

**Second problem**: In some time (it may be 10 minutes or 10 hours) unacked messages appears blocking message processing. How can it be possible? Messages are acked in ensure block which is always executed. Any ideas?

Regards,
Ilya

**Comment by michaelklishin** [comment]
Your code shares a channel between threads. [Please read the docs](http://rubybunny.info/articles/concurrency.html) and see RabbitMQ log file, which means you will eventually run into a concurrency hazard, most notably incorrect frame interleaving on the wire.

Questions do not belong here, use mailing lists.
