### ISSUE TITLE
comments say Channel#basic_ack has default `multiple = false`; code differs

### ISSUE THREAD

**Issue by wconrad** [ruby-amqp/bunny#312]
The implementation of Channel#basic_ack has two required parameters:

     def basic_ack(delivery_tag, multiple)

However, Channel's comments have examples which will only work if the second parameter, `multiple`, has a default of (I guess) `false`:

     #     ch.basic_ack(delivery_info.delivery_tag)

Which is correct?  The docs, or the code?

**Comment by michaelklishin** [comment]
The code. It's a copy-and-paste artifact. We can add a default value for `multiple` (false). Feel free to submit a PR :)

**Comment by michaelklishin** [comment]
Also note that `Channel#basic_ack` is relatively rarely used (primarily by people familiar with other clients). So it took a while to notice.

**Comment by wconrad** [comment]
I'll make  PR to add the default.

**Comment by wconrad** [comment]
It looks like #basic_ack is broken (it's not doing the to_i on the delivery tag).  I'll cook up a PR for that.

#reject, #ack, and #nack are thin wrappers around their #basic_... counterparts.  They wrap the call to the basic method with guarding_against_stale_delivery_tags, like so:

    def nack(delivery_tag, multiple = false, requeue = false)
      guarding_against_stale_delivery_tags(delivery_tag) do
        basic_nack(delivery_tag.to_i, multiple, requeue)
      end
    end

The basic methods do not use that wrapper:

    def basic_nack(delivery_tag, multiple = false, requeue = false)
      raise_if_no_longer_open!
      @connection.send_frame(AMQ::Protocol::Basic::Nack.encode(@id,
          delivery_tag,
          multiple,
          requeue))

      nil
    end

Should the call to `guarding_against_stale_delivery_tags` move into the basic_ methods, or is it intended that the basic_ methods should be able to operate on stale tags?

**Comment by michaelklishin** [comment]
I'm not against moving `guarding_against_stale_delivery_tags`.

**Comment by michaelklishin** [comment]
They are not broken: they are low level methods and don't do everything they possibly could.

**Comment by wconrad** [comment]
Ah.  Then their rdocs are incorrect.  I'll fix 'em.

I'd also like to add tests for the #basic... methods.  The easy thing to do is to copy/modify the tests for the high level functions.  That leaves the tests simple but damp.  I'm not opposed to "damp" in tests-- they shouldn't be dried with a blowtorch--so long as the duplication won't be a source of pain in the future.  What do you think?

**Comment by michaelklishin** [comment]
A small subset of tests can be replicated for the low-level methods (in the same example groups).

**Comment by wconrad** [comment]
There's no test that shows that the value of `multiple` matters when acking.  I'm running into some trouble trying to create one.  Do you want me to ask questions here, or hit the mailing list?

**Comment by michaelklishin** [comment]
`multiple` means "acknowledge all unacknowledged deliveries up to and including this delivery tag".

**Comment by wconrad** [comment]
I'm having trouble with the basic_ack_spec.rb, where it's using `q.message_count`.  For example:

```
  context "with a valid (known) delivery tag" do
    it "gets a depricated message warning for using :ack" do
      ... 
      ch.ack(delivery_details.delivery_tag, true)
      expect(q.message_count).to eq 0
      ch.close
    end
```

This test passes.  But it also passes if you don't ack:

```
  context "with a valid (known) delivery tag" do
    it "gets a depricated message warning for using :ack" do
      ... 
      #ch.ack(delivery_details.delivery_tag, true)
      expect(q.message_count).to eq 0
      ch.close
    end
```

What does queue#message_count _count_?  This makes me think it's counting "ready" messages.

**Comment by michaelklishin** [comment]
That test can be simplified. `Bunny::Queue#message_count` returns the number of messages in Ready state, that is, not yet delivered. One way to test acks would be to close the channel after acking (or not acking) and check the number (on a separate channel) after that. Closing a channel will re-queue all unacknowledged messages.

Or we can use the Ruby HTTP API client which can inspect queues in greatest detail.

**Comment by wconrad** [comment]
The channel close/reopen worked great.

As with #ack and #basic_ack, #reject takes a default:

    def reject(delivery_tag, requeue = false)

but #basic_reject does not:

    def basic_reject(delivery_tag, requeue)

should #basic_reject have the same default as #reject?

**Comment by michaelklishin** [comment]
Yes, as should other related methods.

**Comment by michaelklishin** [comment]
Thank you. I'll release a Bunny 2.0 preview with your improvements some time next week.

**Comment by wconrad** [comment]
Thank you for your patience with my millions of questions.  I don't have any code that depends upon these changes, so for me there's no hurry to release.
