### ISSUE TITLE
How to set priority of consumer queues or messages?

### ISSUE THREAD

**Issue by calebclark** [ruby-amqp/bunny#316]
I have been unable to implement message priorities nor consumer priorities, although I see that RabbitMQ supports both (https://www.rabbitmq.com/priority.html, https://www.rabbitmq.com/consumer-priority.html). I also haven't been able to find any documentation on how to do it.

I did find the high_and_low_priority example within the bunny repository (https://github.com/ruby-amqp/bunny/blob/master/examples/consumers/high_and_low_priority.rb), but it does not actually set a priority on the consumer. The only reason the HIGH messages are consumed first is because the subscribe block is listed first in the script.

Any pointers you can give? I see an open issue for updating the docs with priority queues.

Thanks,

Caleb

**Comment by michaelklishin** [comment]
Bunny uses mailing list for questions.

[How to set :proprity when publishing](https://github.com/ruby-amqp/bunny/blob/master/spec/higher_level_api/integration/message_properties_access_spec.rb#L37).
[Bunny::Queue#subscribe takes a hash of :arguments](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/queue.rb#L188).

**Comment by michaelklishin** [comment]
Both are now document on rubybunny.info.
