### ISSUE TITLE
Publish and Suscribe in the same process

### ISSUE THREAD

**Issue by blanchma** [ruby-amqp/bunny#318]
I'm having problems to do this:

  connection = Bunny.new(amqp_url)
  connection.start

  channel = connection.create_channel
  exchange = channel.topic(topic)

  queue = channel.queue("", {exclusive: true, durable: true, auto_delete: true})
  queue.bind(exchange, routing_key: "#{queue}.in")

  begin
    queue.subscribe do |delivery_info, properties, body|
      puts " Properties: #{properties}"
      puts " Listen: #{body}"
      exit
    end

    exchange.publish("ping", routing_key: "#{queue}.out", persistent: true)

    sleep

If I split the suscribe and publish in different task. It works but together in the same file, not.

**Comment by michaelklishin** [comment]
Please be more specific than "it doesn't work."

What error messages do you see? What's in RabbitMQ log?

**Comment by michaelklishin** [comment]
You publish with the routing key `#{queue}.out` but bind with `#{}.in`. Your messages won't be routed.

Bunny (or any other client) allows you to both consume and publish in the same process.

**Comment by blanchma** [comment]
@michaelklishin It doesn't work means it doesn't receive a message published in another process.

The idea here is an echo: in one side, this process publish to queue_OUT and in other process I'm listening queue_OUT, anything I receive there is send back through queue_IN. 

So the current code is doing prublish to queue_IN and waiting to receive the echo through queue_OUT. When I split this code in two rake tasks I get the echo.

**Comment by michaelklishin** [comment]
See RabbitMQ log, there may be channel exceptions. You can also trace messages with [Firehose](http://www.rabbitmq.com/firehose.html) and [Tracer](http://rabbitmq.com/java-tools.html).

For future references, Bunny does not use issues for questions. That's what mailing lists for.
