### ISSUE TITLE
Timeout::Error: execution expired when opening queue?

### ISSUE THREAD

**Issue by solars** [ruby-amqp/bunny#320]
Hi there,

I've got a rails application that I am switching over to ruby bunny.
I've got the following initializer: https://gist.github.com/solars/e4b99ef4a1483bb0a7d5

I then start rails with rails console and executed the code in the second file above to push to a queue.
I keep getting (on q = ...):

Timeout::Error: execution expired
from /home/solars/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/thread.rb:189:in `sleep'

Can anyone tell me how to fix this?

Thank you,
Christoph

**Comment by michaelklishin** [comment]
Please post questions to Bunny or RabbitMQ mailing list (and provide full stack traces).

**Comment by solars** [comment]
I've added it, thanks
