### ISSUE TITLE
Ack message on separate thread

### ISSUE THREAD

**Issue by nornagon** [ruby-amqp/bunny#321]
I'm building a consumer for metrics data and I'd like to accumulate metric points from a rabbit queue, pass them to a background queue to accumulate & eventually post in bulk to a metrics server, and then ack the messages (~a few 1000 messages at a time) once they've been successfully sent to the metrics server.

What's the best way to trigger acking the messages from a background thread? From the documentation it seems that `Bunny::Channel` is not thread-safe.

My code is roughly:

```
points_acc = Queue.new
Thread.new do
  loop do
    points_to_send = collect_from(points_acc, max: 300)
    if points_to_send.size > 0
      send_to_metrics_server(points_to_send)
    else
      sleep 1
    end
  end
end
queue.subscribe(manual_ack: true, block: true) do |delivery_info, metadata, payload|
  points_acc << payload
  ch.ack(delivery_info.delivery_tag)  # I'd like to not ack until the message has been sent to the metrics server
end
```

**Comment by michaelklishin** [comment]
Please use mailing list for questions.
