### ISSUE TITLE
Timeout::Error while closing channel

### ISSUE THREAD

**Issue by gottfrois** [ruby-amqp/bunny#325]
I'm using Bunny to publish messages in Sidekiq workers using JRuby. I share one connection between Sidekiq threads and before publishing I create and close a new channel using `Session#with_channel` to avoid channel to be shared between threads.

For some reason and not always, the `Timeout::Error: operation did not finish in 4000 ms` is raised. Here is the stack trace:

```
[GEM_ROOT]/gems/bunny-1.7.0/lib/bunny/concurrent/linked_continuation_queue.rb:45 :in `poll`
[GEM_ROOT]/gems/bunny-1.7.0/lib/bunny/session.rb:1156 :in `wait_on_continuations`
[GEM_ROOT]/gems/bunny-1.7.0/lib/bunny/session.rb:497 :in `close_channel`
/home/admin/.rbenv/versions/jruby-1.7.20.1/lib/ruby/1.9/monitor.rb:211 :in `mon_synchronize`
/home/admin/.rbenv/versions/jruby-1.7.20.1/lib/ruby/1.9/monitor.rb:210 :in `mon_synchronize`
[GEM_ROOT]/gems/bunny-1.7.0/lib/bunny/session.rb:493 :in `close_channel`
[GEM_ROOT]/gems/bunny-1.7.0/lib/bunny/channel.rb:231 :in `close`
[GEM_ROOT]/gems/bunny-1.7.0/lib/bunny/session.rb:361 :in `with_channel`
```

My code look like this:

```ruby
connection.with_channel do |channel|
  exchange = channel.default_exchange
  exchange.publish(payload.to_json, properties)
end
```

Any idea what could be wrong?

**Comment by michaelklishin** [comment]
I can't comment without seeing RabbitMQ logs. In any case, I won't spend any time investigating: use March Hare on JRuby (and push JRuby developers to finally release JRuby 9000 because 1.7 has had known I/O bugs for several years now).

**Comment by ysbaddaden** [comment]
I'm experiencing the same error on Ruby 2.1 (not jruby).

I have Celluloid::IO actors sharing a single connection to RabbitMQ (across a single thread but many fibers). When the socket to RabbitMQ somehow gets closed (eg: by introducing a monkey that does a `session.transport.socket.close`), trying to close a channel will hang then raise a Timeout::Error and only then does Bunny will try to recover the closed connection; reopening the channel that should have been closed (which now lives in a dead actor) but that's another problem.

**Comment by michaelklishin** [comment]
@ysbaddaden we cannot help without seeing RabbitMQ logs and a libpcap traffic capture (e.g. with Wireshark).

**Comment by gottfrois** [comment]
Don't know if it can help but my original issue was because I was broadcasting a payload too big which was not allowed and end up trigger bunny timeout exception.
