### ISSUE TITLE
Bunny 2.0.0 unable to connect to rabbitmq cluster

### ISSUE THREAD

**Issue by chandranshu12** [ruby-amqp/bunny#327]
We've set up a RabbitMQ 3.5.3 cluster using Erlang R16B03. We've been using Bunny 1.7.0 for our project and that continues to work fine. Since, we've specified the dependency as >=1.7.0, new EC2 instances coming up today started to install 2.0.0 version starting today and they all failed to connect to the rabbitmq cluster with the following error message:

Bunny::TCPConnectionFailedForAllHosts: Could not establish TCP connection to any of the configured hosts
from C:/ruby193/lib/ruby/gems/1.9.1/gems/bunny-2.0.0/lib/bunny/session.rb:298:in `rescue in start'
from C:/ruby193/lib/ruby/gems/1.9.1/gems/bunny-2.0.0/lib/bunny/session.rb:264:in `start'

Platform information: Windows 2008 server
Ruby version: 1.9.3p545
Bunny: 2.0.0

**Comment by michaelklishin** [comment]
I'm not sure how I can help without seeing any error messages or logs.

**Comment by chandranshu12** [comment]
Updated the issue with the stack trace. I had submitted it accidentally and was updating it while you commented :)

**Comment by michaelklishin** [comment]
You run Ruby 1.9.3, which Bunny 2.0 [no longer supports](https://github.com/ruby-amqp/bunny/blob/master/ChangeLog.md#minimum-required-ruby-version-is-20).

**Comment by chandranshu12** [comment]
Ok, so fixing Bunny version at 1.7.0 is the only way out for us as I see it. Thanks for the info.

**Comment by michaelklishin** [comment]
If you have to use Ruby 1.9.3, yes.
