### ISSUE TITLE
TCP Connection Failure issues with latest gem

### ISSUE THREAD

**Issue by vivek-dhayalan** [ruby-amqp/bunny#329]
I'm getting the following exception with the latest version on bunny (2.0.0)

WARN -- #<Bunny::Session:0x299f410 guest@10.223.19.94:5672, vhost=/, hosts=[10.223.19.94]>: Could not establish TCP connection to 10.223.19.94:5672: 
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/bunny-2.0.0/lib/bunny/session.rb:298:in `rescue in start': Could not establish TCP connection to any of the configured hosts (Bunny::TCPConnectionFailedForAllHosts)
	from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/bunny-2.0.0/lib/bunny/session.rb:264:in `start'
	from rabbit-client-test.rb:12:in `<main>'

Whereas, I'm not seeing the same in 1.7.0. And the following is the code that I'm using :

#!/usr/bin/env ruby
# encoding: utf-8

require "rubygems"
require "bunny"

puts "=> Publishing messages as mandatory"
puts

#conn = Bunny.new
conn = Bunny.new(:host => "10.223.19.94")
conn.start

ch   = conn.create_channel
x    = ch.default_exchange

x.on_return do |return_info, properties, content|
  puts "Got a returned message: #{content}"
end

q = ch.queue("", :exclusive => true)
q.subscribe do |delivery_info, properties, content|
  puts "Consumed a message: #{content}"
end

x.publish("This will NOT be returned", :mandatory => true, :routing_key => q.name)
x.publish("This will be returned", :mandatory => true, :routing_key => "akjhdfkjsh#{rand}")

sleep 0.5
puts "Disconnecting..."
conn.close

**Comment by michaelklishin** [comment]
You run Ruby 1.9.2. Bunny 2.0 requires Ruby 2.0+ — this is in the change log.

**Comment by michaelklishin** [comment]
See #327, as it seems nearly identical.
