### ISSUE TITLE
Version of rabbitmq supported

### ISSUE THREAD

**Issue by pbevin** [ruby-amqp/bunny#332]
The README file says "Make sure you have a recent version of RabbitMQ (> 3.5.3)". Is this meant to be ">= 3.5.3", or is 3.5.4 the minimum supported version? If the latter, it might be less misleading to say ">= 3.5.4".

**Comment by michaelklishin** [comment]
The README says

```
Bunny 1.5.0 (including previews) and later versions only support RabbitMQ 3.3+. Bunny 1.4.x and earlier supports RabbitMQ 2.x and 3.x.
```

Any version starting with 2.0 will work but some features are version-specific. In addition, Bunny assumes authentication failure notifications are available but that only matters when authentication fails.

Please use mailing list for questions in the future.

**Comment by michaelklishin** [comment]
As far as running specs goes, any 3.5.x version is fine. I haven't tried 3.4.x in months but see no reason for that not to work.
