### ISSUE TITLE
Bunny does not work with Rubinius

### ISSUE THREAD

**Issue by katafrakt** [ruby-amqp/bunny#333]
I noticed that while working on a gem depending on bunny: after 1.7.0 bunny no longer works with Rubinius, giving an awful lot of connection errors in tests. The outcome is similar to https://github.com/ruby-amqp/bunny/issues/329 but unlike that, Rubinius is mentioned in README as supported.

I found the "offending" commit - it is https://github.com/ruby-amqp/bunny/commit/b97894285ac38e91758fa575a53ccf2faa62ecfb. Before that only one test is failing on my machine (rbx-2.5.8). After that it's not even possible to scroll to see all errors ;) Unfortunately, I don't have time to investigate further now, but maybe that is something pretty obvious for someone dealing more with Rubinius.

**Comment by michaelklishin** [comment]
If Rubinius does not provide the standard primitives used in b97894285ac38e91758fa575a53ccf2faa62ecfb, it should be fixed in Rubinius.

As much as I admire Rubinius, I don't have the time to support it.

**Comment by katafrakt** [comment]
To be fair I don't see anything there Rubinius does not support. Maybe I was mistaken about this exact commit? I will recheck that in future, 'cause I think you did really great job maintaining Rubinius compatibility.

Meanwhile, thanks for removing misleading information from Readme.

**Comment by katafrakt** [comment]
So I was wrong for some reason and this is the commit where it all started (or rather ended): https://github.com/ruby-amqp/bunny/commit/825f12998f3c5976af1a7528e5216f180b1ecf16

But @michaelklishin you were right anyway: Rubinius socket implementation does not support `Socket.tcp` so it's their fault.

**Comment by zuuno** [comment]
Rbx last versions do now implement `Socket.tcp`.
https://github.com/rubysl/rubysl-socket/issues/11

Just tested again with rbx-3.10 and it works like a charm.

**Comment by katafrakt** [comment]
This is great news, @zuuno! Thank you for checking that.
