### ISSUE TITLE
1.7.0 fails to install on 1.9 ruby because of amq-protocol

### ISSUE THREAD

**Issue by i0rek** [ruby-amqp/bunny#336]
Hello,

thank you for your great work. I noticed that bunny 1.7.0 fails to install on ruby 1.9 because of the way the dependency is specified in the gemspec: https://github.com/ruby-amqp/bunny/blob/1.7.x-stable/bunny.gemspec#L32. It tries to install amq-protocol version 2.0 for me which is ruby 2 only.

Thanks,
Hans

**Comment by michaelklishin** [comment]
You can pin `amq-protocol` to `1.9.2` in your Gemfile. Releasing Bunny `1.7.1` with a more narrow dependency requirement sounds reasonable.

We mention this in the README and docs: JRuby users should use March Hare.

**Comment by i0rek** [comment]
@michaelklishin yes, thats what I am doing. thanks.

**Comment by michaelklishin** [comment]
[Bunny 1.7.1 is out](https://rubygems.org/gems/bunny/versions/1.7.1).

**Comment by i0rek** [comment]
<3
