### ISSUE TITLE
Default recover_from_connection_close to true

### ISSUE THREAD

**Issue by carlhoerberg** [ruby-amqp/bunny#342]
During upgrades of RabbitMQ servers, if `recover_from_connection_close` isn't set to true, client's won't reconnect.

**Comment by carlhoerberg** [comment]
The comment `will make it impossible to force a client to disconnect` in the docs frightens some ppl, they think that they won't be able to force close stale connections either (which of course isn't the case). Also, most ppl have control over their workers, so if they won't to disconnect them, they just shutdown the client, they don't do it from the server, so I don't see a strong reason to default `recover_from_connection_close` to false.

**Comment by michaelklishin** [comment]
I don't feel strongly about this, feel free to submit a PR.

Java client on those that build on top of it do recover from server-sent connection.close and I don't recall any complaints.
