### ISSUE TITLE
wrong argument type Bunny::SSLSocket (expected File)

### ISSUE THREAD

**Issue by carlhoerberg** [ruby-amqp/bunny#345]
This is sometimes raised when connecting with TLS.

```
TypeError: wrong argument type Bunny::SSLSocket (expected File)
/app/vendor/bundle/ruby/2.0.0/gems/bunny-2.1.0/lib/bunny/transport.rb:366:in `initialize'
/app/vendor/bundle/ruby/2.0.0/gems/bunny-2.1.0/lib/bunny/transport.rb:366:in `new'
/app/vendor/bundle/ruby/2.0.0/gems/bunny-2.1.0/lib/bunny/transport.rb:366:in `wrap_in_tls_socket'
/app/vendor/bundle/ruby/2.0.0/gems/bunny-2.1.0/lib/bunny/transport.rb:296:in `post_initialize_socket'
/app/vendor/bundle/ruby/2.0.0/gems/bunny-2.1.0/lib/bunny/session.rb:272:in `start'
```

I believe the problem is that [this line](https://github.com/ruby-amqp/bunny/blob/2.1.0/lib/bunny/transport.rb#L296) is called a second time, when `@socket` already is a `Bunny::SSLSocketImpl` instead of a `Bunny::Socket` as it is the first time (only a `Socket` is accepted by `OpenSSL::SSL::SSLSocket#new`).

**Comment by michaelklishin** [comment]
@carlhoerberg it can be. The `wrap_…` function should return its argument if it's already a TLS socket. Feel free to submit a PR :)
