### ISSUE TITLE
Status of JRuby support

### ISSUE THREAD

**Issue by fgarcia** [ruby-amqp/bunny#348]
According the README there are known bugs with Bunny running on JRuby before 9000, however it still recommends using March Hare. 

If the bugs have already being solved in the latest release. Why is it still recommended?

**Comment by michaelklishin** [comment]
@fgarcia because March Hare is guaranteed to not have any of the bugs we've seen with JRuby in the past. It's too early to tell if 9000 works well or not. MH has a nearly identical API is a lot more efficient: why not just use it?
