### ISSUE TITLE
Can't close connection if RabbitMQ is not responding

### ISSUE THREAD

**Issue by BirknerAlex** [ruby-amqp/bunny#353]
Hello,

I'm running a Ruby Daemon which opens and closes one RabbitMQ connections on demand. If I will close the connection I get a exception. It seems it stucks on closing channels. 

My code for closing the connection:
```ruby 
@rabbitmq_exchange.delete
@rabbitmq_channel.close # throws also an exception -> timeout but catched
@rabbitmq.close # throws the following exception
```
But it also happens if I only do @rabbitmq.close without these other 2 commands.

After this the connection still exists and I can see it over "netstat -natp". If the daemon reopens the connection after a while I will get a 2nd connection. After days I'm leaking a lot of unused connections which are still live.

Is there a chance to force the connection close also if a error occurs? Sometimes RabbitMQ will not close the connection (not always :)) but its really important that the tcp connection will be closed. If working or not.

Exception from Session.close:
```
execution expired (Timeout::Error)
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/concurrent/continuation_queue.rb:25:in `pop'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/concurrent/continuation_queue.rb:25:in `block in poll'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/concurrent/continuation_queue.rb:24:in `poll'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/session.rb:1156:in `wait_on_continuations'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/session.rb:497:in `block in close_channel'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/session.rb:493:in `close_channel'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/channel.rb:231:in `close'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/session.rb:509:in `block (2 levels) in close_all_channels'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/session.rb:509:in `block in close_all_channels'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/session.rb:508:in `each'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/session.rb:508:in `close_all_channels'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/session.rb:341:in `block in close'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/session.rb:1201:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/session.rb:1201:in `ignoring_io_errors'
/usr/local/rvm/gems/ruby-2.2.1/gems/bunny-1.7.0/lib/bunny/session.rb:339:in `close'
/games/sources/daemon/src/application_server.rb:296:in `disable_notifies'
/games/sources/daemon/src/application_server.rb:114:in `block in start_loop'
```

**Comment by michaelklishin** [comment]
See [heartbeats](http://www.rabbitmq.com/heartbeats.html): values in the 10-20 seconds range are safe and will lead to quick TCP connection loss detection by both ends. Continuation timeouts that you see have a configurable interval. Client libraries can either receive a `channel.close-ok` (response) or timeout, nothing else.

**Comment by michaelklishin** [comment]
@BirknerAlex we would really appreciate if questions were asked on the mailing lists and not GitHub issues.

**Comment by BirknerAlex** [comment]
Okay, I just thought it's a issue because I think the timeout comes from the connection state in RabbitMQ. In this case the memory hard limit was reached and the connection was in state "blocking" at RabbitMQ. 

RabbitMQ seems not responding to the closing request.
But If you want I can ask this again in the RabbitMQ Mailing list, just close this issue. Sorry for the inconvenience.

**Comment by michaelklishin** [comment]
@BirknerAlex when you run into an alarm, RabbitMQ stops reading from the socket (on publishing connections). So it cannot respond to `channel.close` by definition.

**Comment by BirknerAlex** [comment]
So there is no "legal" way to close the connection smoothly by the client side? 

The server run into the alarm because there we're to many connections. Without a way to close them it's really hard to solve the memory issue without restarting the whole cluster. 

Should we continue at the Google group?

**Comment by michaelklishin** [comment]
You can force close connections via HTTP API or management UI. You can also [configure your TCP stack](http://rabbitmq.com/networking.html) so that connections time out much quicker.

**Comment by michaelklishin** [comment]
Heartbeat monitor is disabled for blocked connections because we don't want to drop them as resource-driven alarms fairly often do not last for long. But this is an edge case where that isn't a good idea. I don't have a solution in mind (special timeouts will only add to the confusion).

So, closing connections via HTTP API and tuning OS kernel TCP settings is the best we can recommend.

**Comment by carlhoerberg** [comment]
Correct me if I'm wrong Michael but aren't TCP keep-alive disabled by default in RabbitMQ? (We enable it on all servers and are setting the OS TCP keep-alive time to 60s, that way we don't have to relay on AMQP heartbeats)

**Comment by michaelklishin** [comment]
@carlhoerberg they are rather not enabled :/ https://github.com/rabbitmq/rabbitmq-server/blob/master/ebin/rabbit_app.in#L59-65. Perhaps a good idea to change this default for 3.5.6 and future versions.

@essen what's the default in Ranch?

**Comment by essen** [comment]
In Ranch the default is the same as OTP, so false I believe.

**Comment by michaelklishin** [comment]
@essen do you see any downsides to enabling TCP keep-alives by default (in RabbitMQ, not Ranch)?

**Comment by essen** [comment]
I'm not sure it should be enabled by default, because as far as I understand it depends on kernel variables (net.ipv4.tcp_keepalive_time | _probes | _intvl on Linux, similar on Windows, bit different on FreeBSD/Solaris) and those can't be configured from within RabbitMQ itself. The defaults for these values do seem very large on many systems (for example my Linux laptop has a default time of 7200s wait time before the connection is considered dead) so I am not sure enabling it by default would change things very much.

**Comment by carlhoerberg** [comment]
No, 7200s isn't very useful, but by manually changing the OS settings we've found it to be very good. It's weird that Erlang doesn't allow you to modify the socket options, but in Ranch maybe you can?

**Comment by michaelklishin** [comment]
You can configure keep-alive on OTP sockets via options, what kind of modifications did you find "impossible"?

**Comment by carlhoerberg** [comment]
To modify tcp_keepalive_time | _probes | _intvl for the socket.

**Comment by essen** [comment]
You can't change those using the options Erlang provides. Sounds like you can do it with raw TCP options, but those are platform-specific so it's probably not something we can ship with RabbitMQ.

**Comment by carlhoerberg** [comment]
No, definitly, it should be the responsibility of OTP (or Ranch, if it does the communication with the TCP stack/kernel?) to provide that API.

**Comment by essen** [comment]
Ranch is a library built on top of OTP, it uses the same options.

With rare exceptions, OTP only provides an interface to functions and options that are available across all supported systems. Looking at Windows for example, there doesn't seem to be any way to set those options except system-wide by modifying the registry (https://msdn.microsoft.com/en-us/library/windows/desktop/ee470551(v=vs.85).aspx). On Linux, it seems there are options for all three values (http://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/ section 4.2). On FreeBSD it seems these also exist. So Windows would be a problem. Maybe we/someone could try to send a patch to OTP and see if it would get accepted, but chances are low.

**Comment by michaelklishin** [comment]
That said, we'd really appreciate some improvements to our Networking and Production Checklist guides in that area, if @carlhoerberg feels interested in contributing.

**Comment by carlhoerberg** [comment]
No, windows supports it too, it's called SIO_KEEPALIVE_VALS there:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd877220%28v=vs.85%29.aspx

**Comment by michaelklishin** [comment]
That option is from IOCTL. For whatever reason, I don't think Erlang/BEAM uses it on Windows. In any case, this is a subject for erlang-questions.

**Comment by essen** [comment]
It seems like it does but only for scanning interfaces and similar operations.
