### ISSUE TITLE
Why `Exception` instead of `StandardError`

### ISSUE THREAD

**Issue by rudionrails** [ruby-amqp/bunny#357]
Hi,

perhaps this question has been asked in the past already. I went through the old issue list and did not find anything related. Anywho: Why does Bunny use `Exception` instead of `StandardError`?

I am currently rewriting my library [cottontail](https://github.com/rudionrails/cottontail/tree/v2.0.0). It is a wrapper to write Bunny workers. I use rubocop within my code and it complains when rescueing form Exception...

**Comment by michaelklishin** [comment]
Where specifically? In some cases we want to catch things that are not `StandardException`s (the whole name seems really silly to me: how can exception be standard?)

**Comment by michaelklishin** [comment]
Questions belong to the mailing list.

**Comment by rudionrails** [comment]
Not sure why that should be silly. But, there are some [very](https://robots.thoughtbot.com/rescue-standarderror-not-exception) [nice](http://stackoverflow.com/questions/10048173/why-is-it-bad-style-to-rescue-exception-e-in-ruby) [ressources](http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/RescueException) why it is not reccommended to rescue from Exception.

In my case, I just want to recover from a connection loss and retry a defined amount of times before re-raising.

**Comment by michaelklishin** [comment]
@rudionrails those arguments hardly apply to Bunny, which is a library with a fairly small API surface. "Rescuing Exceptions is not idiomatic" is total bullshit.

Again, what specific method are we talking about? `Bunny::Session#start`? Please post a code snippet.
