### ISSUE TITLE
Automatic recovery fails on EmptyResponseError

### ISSUE THREAD

**Issue by gottfrois** [ruby-amqp/bunny#360]
While playing with timeout configuration I encountered the following error after a network recovery:

```
AMQ::Protocol::EmptyResponseError: Empty response received from the server.
```

Here are the following steps to reproduce the error:

1. Install [Toxiproxy](https://github.com/Shopify/toxiproxy) gem
2. Run `toxiproxy`
3. Start an IRB session and run:

```ruby
require 'toxiproxy'

Toxiproxy.populate([
  {
    name: "toxiproxy_rabbitmq",
    listen: "127.0.0.1:5673",
    upstream: "127.0.0.1:5672"
  }
])
```
4. Simulate a latency issue with the following curl command: `curl -i "http://localhost:8474/proxies/toxiproxy_rabbitmq/upstream/toxics/latency" -d '{"enabled":true, "latency":10000}'`
5. Start a new bunny connection.

```ruby
require 'bunny'

conn = ::Bunny.new('amqp://immvnaiq:immvnaiq@127.0.0.1:5673/immvnaiq',
  read_timeout:              5,
  write_timeout:             5,
  connection_timeout:        5,
  network_recovery_interval: 1,
  automatically_recover:     true,
  heartbeat:                 60,
)
conn.start
```

6. Deactivate the fake latency with the following curl command as soon as bunny tries to reconnect, which is visible thanks to the following logs:

```
E, [2015-12-02T12:24:31.687165 #7584] ERROR -- #<Bunny::Session:0x7fe20419adc8 immvnaiq@127.0.0.1:5673, vhost=immvnaiq, addresses=[127.0.0.1:5673]>: Got an exception when receiving data: IO timeout when reading 7 bytes (Timeout::Error)
W, [2015-12-02T12:24:31.687367 #7584]  WARN -- #<Bunny::Session:0x7fe20419adc8 immvnaiq@127.0.0.1:5673, vhost=immvnaiq, addresses=[127.0.0.1:5673]>: Recovering from a network failure...
W, [2015-12-02T12:24:33.691995 #7584]  WARN -- #<Bunny::Session:0x7fe20419adc8 immvnaiq@127.0.0.1:5673, vhost=immvnaiq, addresses=[127.0.0.1:5673]>: Retrying connection on next host in line: 127.0.0.1:5673
```

Curl command to deactivate fake latency:

```
curl -i "http://localhost:8474/proxies/toxiproxy_rabbitmq/upstream/toxics/latency" -d '{"enabled":false, "latency":10000}'
```

Full error backtrace:

```
AMQ::Protocol::EmptyResponseError: Empty response received from the server.
	from /Users/gottfrois/.rvm/gems/ruby-2.2.3/gems/amq-protocol-2.0.0/lib/amq/protocol/frame.rb:60:in `decode_header'
	from /Users/gottfrois/.rvm/gems/ruby-2.2.3/gems/bunny-2.2.1/lib/bunny/transport.rb:245:in `read_next_frame'
	from /Users/gottfrois/.rvm/gems/ruby-2.2.3/gems/bunny-2.2.1/lib/bunny/session.rb:1002:in `init_connection'
	from /Users/gottfrois/.rvm/gems/ruby-2.2.3/gems/bunny-2.2.1/lib/bunny/session.rb:296:in `start'
	from (irb):12
	from /Users/gottfrois/.rvm/rubies/ruby-2.2.3/bin/irb:11:in `<main>'
```

Thanks

**Comment by michaelklishin** [comment]
What's the unit for `latency`? If it's ms then with 10s connection will fail anyway because it's the default protocol handshake value. It is not covered by automatic connection recovery because there is no connection to recover.

Also, what are your expectations here?

**Comment by michaelklishin** [comment]
Yeah, you have socket timeouts of 5s and introduce latency of 10s with a proxy. An exception is expected then.

**Comment by gottfrois** [comment]
Alright I see, maybe a better exception could be raised? Something that could lead us to understand it's a "legitimate" issue due to socket timeout defaults?

Thanks for the quick answer.

**Comment by michaelklishin** [comment]
@gottfrois unfortunately I/O exceptions from sockets are not specific at all. Usually "read no data" is the best you can get. In amq-protocol this currently translates into the exception you're observing. Timeouts isn't the only root cause for empty reads, by the way.

**Comment by gottfrois** [comment]
Alright I get it. Thanks for the help :)
