### ISSUE TITLE
Delayed message output

### ISSUE THREAD

**Issue by schneems** [ruby-amqp/bunny#362]
I had a customer who couldn't get bunny working. When a message was sent none of the debug output would be seen in the listener. After sending many many messages then some would show up. It looked like messages were being lost or not received. It turned out to be `STDOUT.sync = true` was the fix https://github.com/schneems/bunny-demo/commit/c7dd20f157c98d28992276546036e0ae49ee23f0

Not technically a bug in bunny, but a frustrating problem to debug. Not sure if anything can be done, maybe add that line to some of the example code?

**Comment by michaelklishin** [comment]
Bunny should not mess with `STDOUT` settings.

**Comment by schneems** [comment]
I'm not implying that it should

**Comment by michaelklishin** [comment]
If there is an example in the guides that uses debug logging, feel free to add it there with a comment. If not, you can add one (the best place for it is [the Troubleshooting guide](https://github.com/ruby-amqp/rubybunny.info/blob/master/articles/troubleshooting.md)) and also use that setting there.

I don't know what else can be done about it.
