### ISSUE TITLE
Bunny 1.7.1 broken in Jruby 1.7

### ISSUE THREAD

**Issue by soupmatt** [ruby-amqp/bunny#363]
I get the error below just trying to load the gem. 1.7.0 works just fine. I believe the issue was introduced by 63bfc59efeffad8655d1f03ca2f8df15d8785d91. It appears that part of the refactor of the sockets for bunny 2.x leaked back to 1.7.

```
TypeError: wrong argument type Class (expected Module)
          include at org/jruby/RubyModule.java:2022
           Socket at /Users/matt.campbell/.gem/jruby/1.9.3/gems/bunny-1.7.1/lib/bunny/jruby/socket.rb:9
            JRuby at /Users/matt.campbell/.gem/jruby/1.9.3/gems/bunny-1.7.1/lib/bunny/jruby/socket.rb:8
            Bunny at /Users/matt.campbell/.gem/jruby/1.9.3/gems/bunny-1.7.1/lib/bunny/jruby/socket.rb:4
           (root) at /Users/matt.campbell/.gem/jruby/1.9.3/gems/bunny-1.7.1/lib/bunny/jruby/socket.rb:3
          require at org/jruby/RubyKernel.java:1054
           (root) at /Users/matt.campbell/.gem/jruby/1.9.3/gems/bunny-1.7.1/lib/bunny/socket.rb:1
          require at org/jruby/RubyKernel.java:1054
           (root) at /Users/matt.campbell/.gem/jruby/1.9.3/gems/bunny-1.7.1/lib/bunny/socket.rb:3
          require at org/jruby/RubyKernel.java:1054
           (root) at /Users/matt.campbell/.gem/jruby/1.9.3/gems/bunny-1.7.1/lib/bunny.rb:1
          require at org/jruby/RubyKernel.java:1054
           (root) at /Users/matt.campbell/.gem/jruby/1.9.3/gems/bunny-1.7.1/lib/bunny.rb:12
```

**Comment by michaelklishin** [comment]
See https://github.com/ruby-amqp/bunny/issues/356. I'd accept one PR to make it load and mostly work on JRuby, otherwise JRuby is no longer supported: use March Hare.

**Comment by TimothyMDean** [comment]
@michaelklishin Does March Hare work at all on JRuby 1.7.x (Ruby 1.9.3)? If not, then Bunny 1.7.x seemed to be the only option for those of us stuck on an older version of JRuby. Since Bunny 1.7.0 seems to work on JRuby 1.7 but Bunny 1.7.1 does not, do we have any other option except explicitly pinning ourselves to Bunny 1.7.0?

**Comment by michaelklishin** [comment]
March Hare requires JRuby 9K.

I have no interest in maintaining JRuby 1.7 support, it has too many I/O bugs and incompatibilities.

**Comment by michaelklishin** [comment]
There were March Hare versions that worked on JRuby 1.7, that project is several years old.

**Comment by TimothyMDean** [comment]
Thanks @michaelklishin  - I understand your lack of interest in maintaining JRuby 1.7 support.

Unfortunately, I am stuck with JRuby 1.7 for a while and I have no control over changing it. It's tied to the fact that JRuby 9000 requires Java 7, which would require our platform to upgrade its app server and a whole lot more. I am pressuring the owners of the platform to move forward, but I can only influence them so far.

Given that reality, do you have any advice on how to best live with this situation? Should we stick to Bunny 1.7.0 and avoid any later 1.7.x updates? Are there any other options I should consider?

I realize that none of this is your problem, but given your significant experience in this area I'd love to know if you have any practical recommendations for me.

Thanks

**Comment by michaelklishin** [comment]
Try March Hare versions in reverse chronological order and see which one works on JRuby 1.7. RabbitMQ Java client still supports JDK 6.
