### ISSUE TITLE
Logs and statistics

### ISSUE THREAD

**Issue by nicohvi** [ruby-amqp/bunny#371]
First off, love the gem! Great work :+1: 

This might be more suitable to post on the mailing list, but I really don't like the feel of Google Groups. If I should move this please inform me and I'll do so. :)

Anyway, I was wondering how you guys monitor the memory usage and/or connections of Bunny/RabbitMQ? I'm currently tailing the logs in `/usr/local/var/logs/rabbitmq/`, but they're not very interesting.

Just looking for thoughts and ideas, cheers :+1:

**Comment by michaelklishin** [comment]
This is exactly the kind of question for the mailing list.

**Comment by nicohvi** [comment]
Okay, cheers!
