### ISSUE TITLE
Testing with latest rabbitmq-server.

### ISSUE THREAD

**Issue by userlocalhost2000** [ruby-amqp/bunny#373]
Could you please consider test with RabbitMQ that is master branch of [rabbitmq-server](https://github.com/rabbitmq/rabbitmq-server).

The rabbitmq-server version in Travis-CI is 3.5.7, which doesn't conform with lastest rabbitmq-server.
Other implementation of rabbitmq-client (e.g. [rabbitmq-erlang-client](https://github.com/rabbitmq/rabbitmq-erlang-client)) builds latest one and tests with it.

If you agree with this, I'll enhance `bin/ci/before_build` script to build and run it.

**Comment by michaelklishin** [comment]
Testing against multiple versions is fine. However, Java, .NET, and Erlang clients are developed by the same team as RabbitMQ and Bunny isn't, at least it is not a Pivotal project.

I'd test against `3.5.7` and the most recent `3.6.x` release (currently `3.6.0`).

**Comment by userlocalhost2000** [comment]
Thank you for your reply.

I understood the reason why Bunny is dealt with other organization of rabbitmq.
I'll test with multiple version of RabbitMQ.

**Comment by michaelklishin** [comment]
@userlocalhost2000 thank you!
