### ISSUE TITLE
Timeout::Error calling channel.topic

### ISSUE THREAD

**Issue by stefankroes** [ruby-amqp/bunny#378]
Hi!

I hope I'm not having this issue because I'm doing something wrong but I think this is an issue in bunny.

```
Timeout::Error: Timeout::Error in /vendor/bundle/ruby/2.2.0/gems/bunny-2.2.2/lib/bunny/concurrent/continuation_queue.rb:33

/vendor/bundle/ruby/2.2.0/gems/bunny-2.2.2/lib/bunny/concurrent/continuation_queue.rb#L33 in block in poll
/vendor/bundle/ruby/2.2.0/gems/bunny-2.2.2/lib/bunny/concurrent/continuation_queue.rb#L30 in synchronize
/vendor/bundle/ruby/2.2.0/gems/bunny-2.2.2/lib/bunny/concurrent/continuation_queue.rb#L30 in poll
/vendor/bundle/ruby/2.2.0/gems/bunny-2.2.2/lib/bunny/channel.rb#L1774 in wait_on_continuations
/vendor/bundle/ruby/2.2.0/gems/bunny-2.2.2/lib/bunny/channel.rb#L1176 in block in exchange_declare
/usr/local/lib/ruby/2.2.0/timeout.rb#L88 in block in timeout
/usr/local/lib/ruby/2.2.0/timeout.rb#L98 in call
/usr/local/lib/ruby/2.2.0/timeout.rb#L98 in timeout
/vendor/bundle/ruby/2.2.0/gems/bunny-2.2.2/lib/bunny/channel.rb#L1175 in exchange_declare
/vendor/bundle/ruby/2.2.0/gems/bunny-2.2.2/lib/bunny/exchange.rb#L245 in declare!
/vendor/bundle/ruby/2.2.0/gems/bunny-2.2.2/lib/bunny/exchange.rb#L83 in initialize
/vendor/bundle/ruby/2.2.0/gems/bunny-2.2.2/lib/bunny/channel.rb#L344 in new
/vendor/bundle/ruby/2.2.0/gems/bunny-2.2.2/lib/bunny/channel.rb#L344 in topic
```

Below the stacktrace above is the following code in my project:

```
    def exchange
      @exchange ||= channel.topic 'new_requests', durable: true
    end
```

We are using bunny from a bunch of sidekiq workers. When the workers are restarted, this error occurs a few times (1-3 jobs fail) and afterwards jobs start processing normally.

**Comment by michaelklishin** [comment]
Continuation timeouts cannot be considered Bunny issues. You can bump the timeout and whenever there's a surge of operations, this is not entirely surprising.

**Comment by stefankroes** [comment]
Dear Michael, 

Thank you for your explanation. I'm left with a couple of questions. I really appreciate it if you could answer them, also for the sake of others googling this:

* I see the default timeout is 4000ms. Do you suggest initializing Bunny with a higher value for `:continuation_timeout`? What value would be more suited?
* RabbitMQ has been running normally is not particularly busy while I restarted Sidekiq, why would it take over 4 seconds to reconnect?

With kind regards,

Stefan

**Comment by michaelklishin** [comment]
@stefankroes default value depends on the Bunny version used. We bumped it to 15 seconds recently. I don't know anything about your code but can imagine a surge of operations during Sidekiq startup because Sidekiq is supposedly concurrent. Those operations are probably all on a shared connection and thus have to be synchronised.

Continuation timeouts have nothing to do with TCP or AMQP 0-9-1 connections, they are per-operation timeouts in the client.

**Comment by michaelklishin** [comment]
I don't know what value will work for you. Try 10 or 15. I don't recall seeing any continuation timeout issue reports after we bumped it to 15 seconds, barring cases where certain nodes are unreachable (in which case some operations are expected to time out).

**Comment by stefankroes** [comment]
We are on version 2.2.2, I checked and the 15 second default timeout is in that version. I would much rather find the underlying issue in our code than increase the timeout further.

One thing is very strange: When I restart our Sidekiq workers, the timeouts are reported almost immediately afterwards, easily within 15 seconds from restarting.

Is there some documentation that would help me to better understand these continuation timeouts and how to avoid them?

Some more information about our setup:

* Multiple Sidekiq workers (threads) all share a single Bunny client through a singleton pattern
* The Rails environment is preloaded and initialized before `Bunny.new` is even called
* Below is a simplification of all the code that leads up to the problem

```
bunny = Bunny.new spec:                  '0.9.1'
                  port:                  5672
                  heartbeat:             20
                  automatically_recover: true
                  host:                  'some-host'
                  vhost:                 '/some-vhost'
                  user:                  'some-user'
                  pass:                  'some-pass'

bunny.start
channel = bunny.create_channel
channel.topic 'new_requests', durable: true # Blows up
```

**Comment by michaelklishin** [comment]
@stefankroes imagine that you have 30 threads starting up and all declaring an exchange (and probably doing more things) at once. Connection has to synchronise them, otherwise on the wire data will be incorrect. So you have at least 30 operations from 30 threads all starting around the same time,
having roughly 15 seconds from start (by default) to complete.

After this initial burst you don't have anywhere near that kind of concurrency, so you never hit the timeouts.

I'm pretty sure that if you bump it to 30 (which is not unreasonable), you won't see any timeouts.

**Comment by stefankroes** [comment]
But how can it be that the timeouts occur almost instantly after restarting? Shouldn't at least 15 seconds pass before a 15 second timeout can occur?

**Comment by michaelklishin** [comment]
I don't know. Bunny doesn't do anything particularly creative. Ruby's `Timeout` is flawed in multiple ways but again, it doesn't do anything too complicated (starts a new thread that throws an exception in the original one after a period of time). So if you restart the entire VM, there cannot be any previous state left. If you don't restart the VM but simply a number of threads in it (again, I know next to nothing about Sidekiq), the above note about how `Timeout` works is a plausible answer.

**Comment by stefankroes** [comment]
Ok, thx for your help! I'm going to see about synchronizing exchange declaration myself

**Comment by stefankroes** [comment]
Update: I've not been able to reproduce the problem since changing my code in the initial issue description to:

```
    NewRequestExchangeMutex = Mutex.new

    def exchange
      NewRequestExchangeMutex.synchronize { @exchange ||= channel.topic 'new_requests', durable: true }
    end
```

**Comment by ericmason** [comment]
This seems to be something other than the need for a longer timeout since @stefankroes is saying he is getting a timeout in less than 15 seconds.
