### ISSUE TITLE
Can't access exchange

### ISSUE THREAD

**Issue by rubycut** [ruby-amqp/bunny#38]
I am trying to write to exchange in passive mode with user who have only write permission to rabbitmq-server.

As far as I understood from documentation, it should be possible, using passive exchange declaration:

sudo rabbitmqctl set_permissions -p /x  user '' 'my_exchange'  ''

then test.rb:

```
b  Bunny.new(:host => 'localhost',:vhost=> "/x", :port => 5672,:user=>"user",:pass=> "123",:logging=>true )
b.start
e = b.exchange("my_exchange", :passive => true)
```

I checked my_exchange already exists, log is following:

```
I, [2012-02-13 12:28:11#11644]  INFO -- send: #<Qrack::Transport::Method:0x7f1804d7f348 @channel=1, @payload=#  <Qrack::Protocol::Exchange::Declare:0x7f1804d7f848 @durable=nil, @passive=true, @nowait=nil, @exchange="my_exchange",   @internal=nil, @type=:topic, @ticket=1, @arguments=nil, @auto_delete=nil>>
I, [2012-02-13 12:28:11#11644]  INFO -- received: #<Qrack::Transport::Method:0x7f1804d7d980 @channel=1, @payload=#<Qrack::Protocol::Channel::Close:0x7f1804d7d818 @class_id=40, @reply_text="ACCESS_REFUSED - access to exchange 'my_exchange' in vhost '/x' refused for user 'user'", @reply_code=403, @method_id=10>>
```

Why would that be? plus, it seems bunny is sending correct info. So I am not sure if this is bunny bug, it seems to me that it's not likely that rabbitmq-server would have such bug, I am using rabbitmq-server 2.5.1 and newest  bunny 0.7.9.

If I give config access, then it works, but then what was the point of passive declaration.

**Comment by macgyver13** [comment]
@rubycut did you ever open an issue for this configure permission issue

**Comment by michaelklishin** [comment]
I'm pretty sure it's simply a case of insufficient [permissions configured](http://www.rabbitmq.com/access-control.html) (e.g. a new vhost was created but the user was never granted any permissions to it), there is nothing to report. This is mailing list material.

**Comment by macgyver13** [comment]
Thank you michael for the fast response.  Similar to rubycut I can only bind to exchange if I have configure permission for the exchange granted, granting read, write .* alone is not adequate.

I have a need for a client to be able to bind to any exchange using a shared user login, but I would prefer that the client not be able to destroy exchanges.

**Comment by michaelklishin** [comment]
This is not a support forum.

`exchange.delete` requires `configure` permissions while `{queue, exchange}.{bind, unbind}` requires `read` and `write` permissions on source/destination, as [explained in the docs](http://www.rabbitmq.com/access-control.html).
