### ISSUE TITLE
undefined method `queue' for #<AMQ::Protocol::Basic::ConsumeOk:0x007f4804cd5b60>

### ISSUE THREAD

**Issue by bhelx** [ruby-amqp/bunny#386]
I believe this may be a duplicate of this issue but I wanted to ask to make sure I'm interpreting this error correctly https://github.com/ruby-amqp/bunny/issues/188

We are currently seeing this error sporadically when trying to call `queue` on a channel.

```
undefined method `queue' for #<AMQ::Protocol::Basic::ConsumeOk:0x007f4804cd5b60>
```

I checked the code and it appears that we were in fact sharing the channel between threads. I've created a pull request to address this issue, but I wanted to get some advice on whether this is the right fix and if there is a good way to test that i've fixed the problem.

**Comment by michaelklishin** [comment]
@bhelx yes, sharing a channel between threads would lead to request-response mismatches like this one to be observed by the client. We are not interested in adding more synchronisation to support this scenario. Simply use a separate channel in every thread you use.

On top of that, I don't see any pull requests submitted for Bunny as of right now.

**Comment by bhelx** [comment]
@michaelklishin thanks for the quick reply. I was referring to a pull request within our application experiencing this issue. It changes our code to use one channel per thread as you suggested.

I was also hoping for some advice on how I may be able to reproduce the issue in our application as it seems to be random and doesn't show up in tests. Do you think it could be reproduced under some load?

**Comment by michaelklishin** [comment]
Create N threads that each perform synchronous operations (that expect a response, e.g. `queue.declare` or `basic.consume`) on a shared channel. It should not take long to run into this concurrency hazard with just a few threads.

**Comment by bhelx** [comment]
Thanks a lot for your advice! I want to make sure I've fixed this issue before it starts causing problems.
