### ISSUE TITLE
bunny slows down as the number of queues grow

### ISSUE THREAD

**Issue by anilagarwal1** [ruby-amqp/bunny#388]
I am observing that the frequency of publish messages going unpublished grows as the number of queue grows.

For example:
for first 1000 queues i lost 1 in 100 message
for next 1000 queues i lost >1 in 100 message #total queues this time is 2000
for next 1000 queues i lost >3 in 100 message #total queues this time is 3000

I am not sure, if this is an issue or should be a question. pardon my ignorance.

**Comment by michaelklishin** [comment]
Questions belong to the mailing list. Please post your actual code and explain how you conduct the test. I do not understand what you're trying to do or what the issue is.

**Comment by anilagarwal1** [comment]
Thanks, i posted the same there. https://groups.google.com/forum/#!forum/ruby-amqp
