### ISSUE TITLE
Message persistence defaults

### ISSUE THREAD

**Issue by stefansedich** [ruby-amqp/bunny#392]
Reading the documentation I got the impression that message persistence was not the default when in fact if you do not set this value the delivery_mode appears to be set to 2 by default.

http://rubybunny.info/articles/durability.html

A quick update to the docs could indicate this and make it clearer (I can submit a PR but I must be blind and could not find the docs repo).

**Comment by michaelklishin** [comment]
It's [right here](https://github.com/ruby-amqp/rubybunny.info) :)
