### ISSUE TITLE
Seemingly incorrect implementation of ReaderLoop#stopped?

### ISSUE THREAD

**Issue by Zhomart** [ruby-amqp/bunny#397]
There is a piece of code that should check status in reader_loop.rb

```
    def stop
      @mutex.synchronize { @stopping = true }
    end

    def stopped?
      @mutex.synchronize { @stopped = true }
    end

    def stopping?
      @mutex.synchronize { @stopping = true }
    end
```

Is this intended that `ReaderLoop#stopped?` updates value of variable `@stopped`?

**Comment by michaelklishin** [comment]
See the comment in https://github.com/ruby-amqp/bunny/commit/1b807b14421798728f545ad5a0866d91e2324996, but the same mistake was repeated months later in https://github.com/ruby-amqp/bunny/commit/f829a4e9fabd458b6d8a88f30b3a129030ddaaf4.

Feel free to submit a PR and add a basic test. Thank you.
