### ISSUE TITLE
Close to 100% CPU usage on MRI 2.3.0

### ISSUE THREAD

**Issue by klobuczek** [ruby-amqp/bunny#399]
I'm running the modified example from the RabitMQ website https://www.rabbitmq.com/tutorials/tutorial-six-ruby.html connecting from a client to a remote server. While waiting for the response on the client the CPU usage is close to 100% on OSX and ruby 2.3.0. Is the client implemented using polling?

**Comment by michaelklishin** [comment]
If by "the client" you mean the library, [it uses `IO.select` in a separate thread](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/reader_loop.rb). If you mean "the RPC client used in the tutorial", it does not use `basic.get` (`Bunny::Queue#pop`) and is just an example.

Use a profile to find out what's going on.

**Comment by michaelklishin** [comment]
Oh, and you are running "a modified example." — I'm not sure what kind of feedback you are aiming for without providing the code. In any case, use a profiler.

**Comment by klobuczek** [comment]
The only modification I did to it was to point to a non local server to make sure there is nothing else running on the client machine, especially that the long running server is not affecting the client. Sorry I am just evaluating different message brokers, so really don't want to get into details yet. But are you saying the tutorial example rpc_client is not implemented optimally and there are better ways to do that?

**Comment by klobuczek** [comment]
My apologies. The CPU spike was due to my wrong configuration. There was an rpc server still running on my local  and picking up jobs. My bad.
