### ISSUE TITLE
Not possible to connect to another server when the RABBITMQ_URL env var is set

### ISSUE THREAD

**Issue by lailsonbm** [ruby-amqp/bunny#401]
When there is a `RABBITMQ_URL` var set in the environment, it's not possible to create a Bunny client to another server with a connection string. Bunny will simply ignore the string given in the constructor and use the `RABBITMQ_URL` instead. To make it clear:

```
# Given that ENV['RABBITMQ_URL'] == 'amqp://foo:1234@server-a.rmq.com/host-a'

Bunny.new
=> #<Bunny::Session:0x7fe37325a248 foo@server-a.rmq.com:5672, vhost=host-a, addresses=[server-a.rmq.com:5672]>

Bunny.new('amqp://bar:5678@server-b.rmq.com/host-b')
=> #<Bunny::Session:0x7fe3743aa638 foo@server-a.rmq.com:5672, vhost=host-a, addresses=[server-a.rmq.com:5672]>
```

The problem happens due to the way the param is handled in `Session`: https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L129

This behavior is confusing and not documented anywhere. I'd be happy to open a pull request to fix that, but before I'd like to check if this is expected in some way. Thoughts?

**Comment by michaelklishin** [comment]
You are expected to use one or the other. Using both will certainly confuse some.

**Comment by lailsonbm** [comment]
Thanks for the quick response, @michaelklishin. However, I still think this is a bug for three reasons:

1. it's limiting, since when the RABBITMQ_URL env var is set there is simple no way to create a Bunny client to other server (at least not with a connection string).
2. it's tricky, since the given connection string is silently ignored by Bunny.
3. and it's not consistent with [other](https://github.com/petergoldstein/dalli/blob/master/lib/dalli/client.rb#L34) [Ruby](https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L385) [clients](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/client.rb#L88-L92), which use env vars only as default value, when a connection string is not passed.

And the fix is very easy to do. Like I said, I'd be happy to open a PR with it. Otherwise, we should at least document this behavior and log a warning when the env var overrides the given connection string.

**Comment by lbrito1** [comment]
Just wanted to weigh in: while this may not be exactly a bug _per se_, IMHO it definitively is a code smell and violates the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment): I'd expect that a valid argument will override any associated environment variables, not the other way around. If this is not the case, I would expect at least some kind of warning in the form of an exception or even a printed message.

**Comment by michaelklishin** [comment]
@lbrito1 I'm all for producing a warning. Feel free to look into a pull request. Changing this behaviour will potentially break a lot of existing applications at a really small gain, so I'm not convinced it's worth doing.

**Comment by O1O1O1O** [comment]
FYI you just need to update to 2.3 or later since it now has the options argument defaulted from the environment, but does not override if specified: https://github.com/ruby-amqp/bunny/blob/2.4.x-stable/lib/bunny/session.rb#L128

**Comment by michaelklishin** [comment]
@O1O1O1O I believe you mean Bunny `2.4.0`, which includes https://github.com/ruby-amqp/bunny/commit/e5d8cb36447fa36bc7a7e353cfe62f8861564465.

**Comment by O1O1O1O** [comment]
I didn't, but you're right, thanks for the correction. I was looking at a change baeda638cdb4a31e553f4f8a99f3f43bdab356da in the 2.3.x branch but it didn't make it in until 2.4.0 release as you pointed out.

**Comment by lailsonbm** [comment]
Nice! Thanks for the heads up, @O1O1O1O, @michaelklishin!
