### ISSUE TITLE
Proper usage of Confirm Select

### ISSUE THREAD

**Issue by podung** [ruby-amqp/bunny#404]
My understanding is that while in confirm mode both the publisher and the server track the sequence of messages and the server reports back the message sequence when ack'ing/nack'ing.   From [Rabbitmq](https://www.rabbitmq.com/confirms.html):

> Once a channel is in confirm mode, both the broker and the client count messages (counting starts at 1 on the first confirm.select). The broker then confirms messages as it handles them by sending a basic.ack on the same channel. The delivery-tag field contains the sequence number of the confirmed message.

In looking at Bunny's code, I think it is necessary to track the sequence on my own so I can map the nacked_set back to the conceptual messages I published:

```ruby
ch.confirm_select

messages = {}
1.up_to(100).times do
  msg = "publishing #{i}"

  messages[i] = msg
  x.publish(msg)
end

success = ch.wait_for_confirms

unless success
  failed_messages = messages.select { |seq,msg| nacked_set.include? seq }
  
  puts "Server nacked following messages:"
  puts failed_messages.join("\n")
end
```

Is this correct?

In my case only one thread will be accessing the channel, so the approach seems valid, just a little clunky.  If this is the correct usage, I'll clean up my example and do a PR to update the publisher confirm example with this info.

**Comment by michaelklishin** [comment]
Bunny does not map sequence numbers to messages, so basically yes.

**Comment by michaelklishin** [comment]
Please post questions to the mailing list in the future.
