### ISSUE TITLE
Add support for Celluloid::IO sockets

### ISSUE THREAD

**Issue by thedrow** [ruby-amqp/bunny#413]
Bunny does not currently expose a mechanism to inject a custom socket class through it's API.
In order to cooperate with Celluloid::IO's reactor we either need that API or to provide support for it by checking if `Celluloid::IO.evented?` is equal to true.
What do you think?

**Comment by michaelklishin** [comment]
Bunny has a transport abstraction, would extracting a shared transport and making transport configurable (in case it isn't, which is likely) help your case?

**Comment by michaelklishin** [comment]
Never mind, I see your PR. That solution is also acceptable.

On Wed, Jun 8, 2016 at 12:40 PM, Omer Katz <notifications@github.com> wrote:

> Bunny does not currently expose a mechanism to inject a custom socket
> class through it's API.
> In order to cooperate with Celluloid::IO's reactor we either need that API
> or to provide support for it by checking if Celluloid::IO.evented? is
> equal to true.
> What do you think?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ruby-amqp/bunny/issues/413>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAAEQrEpEIl-pMGFsaofVp7Kbzc6OMJTks5qJo33gaJpZM4IwxlL>
> .
>



-- 
MK

Staff Software Engineer, Pivotal/RabbitMQ

**Comment by michaelklishin** [comment]
#414 was closed as too intrusive. Celluloid support should be opt-in and explicit (as new connection option).

**Comment by thedrow** [comment]
So how would you like me to implement it and where?
The only place a socket is opened is in `Bunny::Socket`. Do you want me to add a socket class to `Bunny::Socket` and provide a flag to both session and transport?

**Comment by michaelklishin** [comment]
The PR for this was never fully addressed. Closing unless someone else has good reasons for making alternative socket implementations supported.
