### ISSUE TITLE
Logging to a provided logger sends message to progname

### ISSUE THREAD

**Issue by bmedici** [ruby-amqp/bunny#416]
Hi,

When using an already initialized logger, Bunny seems to send the message a the progname attribute.
I'm using a custom formatter:
`self.formatter = proc do |severity, datetime, progname, message|`
and messages are received in progname and not in message.
Is there a reason for that ? I've seem "init_default_logger_without_progname" in the code but did no't find out the logic.
Thanks

**Comment by michaelklishin** [comment]
@bmedici I doubt there's a big idea behind this. Does it work as expected with the default formatter?

**Comment by michaelklishin** [comment]
Closing as there was no response. If someone knows how to detect a custom formatter and log differently, we would consider changes in this area.
