### ISSUE TITLE
Timeout error when doing queue.pop

### ISSUE THREAD

**Issue by Bogdan-D** [ruby-amqp/bunny#417]
You have queue pop method, which should always return [nil,nil,nil] if there are no messages in queue. 
[Here is a doc](http://reference.rubybunny.info/Bunny/Queue.html#pop-instance_method)

But i've got Timeout::Error exception for some long-running responses. 

Here is stacktrace:

```
gems/bunny-2.3.1/lib/bunny/concurrent/continuation_queue.rb:33:in `block in poll': Timeout::Error (Timeout::Error)
    from gems/bunny-2.3.1/lib/bunny/concurrent/continuation_queue.rb:30:in `synchronize'
    from gems/bunny-2.3.1/lib/bunny/concurrent/continuation_queue.rb:30:in `poll'
    from gems/bunny-2.3.1/lib/bunny/channel.rb:1791:in `wait_on_basic_get_continuations'
    from gems/bunny-2.3.1/lib/bunny/channel.rb:622:in `basic_get'
    from gems/bunny-2.3.1/lib/bunny/queue.rb:249:in `pop'
```

Here is sample usage:

```ruby
 loop do
        delivery_info, prop, body = queue.pop(manual_ack: true)

        if body && prop && prop[:correlation_id] === call_id
          channel.ack(delivery_info.delivery_tag, true)
          return ReadMsg.read(body)
        end

        sleep 0.01
end
```

**Comment by michaelklishin** [comment]
Yes, all synchronous operations can time out for one reason or another: from networking problems to RabbitMQ being very busy to timeouts being set too low. Your consumer application needs to be prepared for that.

**Comment by michaelklishin** [comment]
Please post questions to the mailing list in the future (Bunny's own or rabbitmq-users).

**Comment by Bogdan-D** [comment]
i think it's a bug unless it's documented.

**Comment by michaelklishin** [comment]
@Bogdan-D where would you like to see it documented?
