### ISSUE TITLE
Exchanges not respecting no_declare on `recover_from_network_failure`

### ISSUE THREAD

**Issue by arfrank** [ruby-amqp/bunny#421]
After a network recovery exchange calls `declare!` (https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/exchange.rb#L223), even if the exchange has `opts` set for `no_declare` as is respected upon initialize (https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/exchange.rb#L87).

**Comment by arfrank** [comment]
#422 should fix this issue

**Comment by michaelklishin** [comment]
@arfrank I'm afraid it calls a method that does not exist.

**Comment by michaelklishin** [comment]
Related to #337.
