### ISSUE TITLE
Question about subscribe concurrency

### ISSUE THREAD

**Issue by austinthecoder** [ruby-amqp/bunny#423]
This isn't an issue, just a question. Sorry for posting here. I'm not sure the best place to ask.

To achieve concurrency, would this work?

```ruby
require 'bunny'

queue = Bunny.new.start.create_channel.queue 'my_queue'

block = ->(delivery_info, metadata, payload) do
  puts "received: #{payload}"
end

9.times { queue.subscribe &block }

queue.subscribe block: true, &block
```

Is there a better way? Hoping to reduce Heroku costs by having more workers per dyno.

**Comment by michaelklishin** [comment]
Please post questions to the mailing list.

**Comment by michaelklishin** [comment]
This question is [answered in the docs](http://rubybunny.info/articles/concurrency.html). On CRuby it won't matter much. [Sneakers](http://jondot.github.io/sneakers/) in part works around this by combining OS processes and threads. I'm not a Heroku expert but it should work there.
