### ISSUE TITLE
Allow handling more channel-level errors with Channel#on_error

### ISSUE THREAD

**Issue by mitio** [ruby-amqp/bunny#429]
In rare cases, publishing a message may result in a channel-level error and closing of the channel by RabbitMQ.

For example, publishing via a deleted exchange (as [demonstrated in this snippet](https://gist.github.com/mitio/059f9938eee06f820d57c6b7f59fcc9a)) would result in
`AMQ::Protocol::Channel::Close` with a `@reply_code` of `404` and a `reply_text` of `NOT_FOUND - no exchange '…' in vhost '…'"`.

There is currently no way to handle such errors in client code. The closest thing to a handler for them is `Channel#on_error`, but currently it's said to handle only errors after basic.ack, basic.reject and basic.nack and is triggered only if the error from RabbitMQ matches the following:

```ruby
def channel_level_exception_after_operation_that_has_no_response?(method)
  method.reply_code == 406 && method.reply_text =~ /unknown delivery tag/
end
```

I'm not sure if extending the scope of `on_error` would be the best way to handle this, but I think there should exist an API for this.

**Comment by michaelklishin** [comment]
Sorry but this will not be considered. `Bunny::Channel#on_error` exists only because errors can be server-sent and some protocol methods have no responses by design, therefore we cannot use continuations and raise exceptions for them.

We don't want to have 2 ways to do error handling where we can help it.

**Comment by mitio** [comment]
Fair enough. Having a single and consistent error handling mechanism makes sense.

Do I understand correctly, though, that you are suggesting continuations are the way for client code to handle such error conditions?

Or are you agreeing that there is no optimal way to handle these errors (beyond relying on `wait_for_confirmations` to timeout), but you will not consider any changes in Bunny to allow clients to handle them in other ways?

**Comment by michaelklishin** [comment]
For operations that have a response (e.g. `queue.declare` or `queue.bind`), Bunny already uses continuations and throws exceptions. `Bunny::Channel#on_error` exists for cases when that's not technically possible.

**Comment by mitio** [comment]
Hey Michael, thanks for the clarification and patience! I really appreciate it.

I accept that you don't want `on_error` to be enhanced and I'm not pushing for it.

I just want to point out that I demonstrated a case where `basic_publish` would result in an immediate channel close frame instead of an ack or nack and there's no user facing method people can use to handle this case. Yes, this frame is pushed to `@continuations`, but one can't simultaneously wait for both `wait_on_continuations` and `wait_for_confirms` and has to pick one. The "happy path" is waiting for confirmations after publishing and it will just timeout because of the lack of handling of this case.

Are you positive that you don't want Bunny to handle such cases (a channel close after `basic_publish`) in any user accessible way? Isn't it feasible to release all confirms continuations in this case? E.g. call `release_all_continuations` in `close!` or in `handle_method`?

If you're positive that's not desirable, I will not push further. Thanks again for your time.

**Comment by michaelklishin** [comment]
@mitio I never said that I don't want that case to be handled better. I said that I don't want to turn the API into a mess. `release_all_continuations` exists for cases like these.

**Comment by mitio** [comment]
Okay, so would it be acceptable to call `release_all_continuations` in `close!` or in `handle_method` in case of a channel close frame?

**Comment by michaelklishin** [comment]
@mitio I think so. That's probably the best we can do with the API build around continuations. Other clients with similar design (e.g. Java and .NET) do similar things, although Java and C# offer decent concurrency primitives in the standard library, so there are more options.
