### ISSUE TITLE
Expose no-wait

### ISSUE THREAD

**Issue by baelter** [ruby-amqp/bunny#433]
From amqp spec section 1.1:
"[do not send reply method] If set, the server will not respond to the method. The client should not wait for a reply method. If the server could not complete the method it will raise a channel or connection exception."

**Comment by michaelklishin** [comment]
This may or may not fit into the continuation mechanism we have but Java and .NET clients are quite similar in their channel implementation, so it should be OK.

**Comment by michaelklishin** [comment]
I'm afraid will seriously mess with our continuation implementation so unless someone can prove me wrong, this sounds like something not worth the effort. Sorry.

**Comment by michaelklishin** [comment]
I have an idea about how `:nowait` may be supported, we'll see how a spike goes.

**Comment by michaelklishin** [comment]
So I've noticed a couple of issues with my approach:

 * For a couple of `Bunny::Channel` methods in the lower-level API it will require breaking signature changes.
 * For all of them it will require returning `nil` where they currently never do. This will break method chaining in the API.

I therefore consider it not worth the changes. Bunny focuses on ease of use and some of the wins in that are come from the fact that it's historically ignored `:nowat`.

**Comment by baelter** [comment]
Fair enough, thx for looking into it.
