### ISSUE TITLE
Could not establish TCP connection

### ISSUE THREAD

**Issue by MarioRuiz** [ruby-amqp/bunny#434]
I am trying to connect to my MQ on Ruby 2.2.4 but I am getting this message : 
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bunny-2.5.1/lib/bunny/session.rb:322:in `rescue in start': Could not establish TCP connection to any of the configured hosts (Bunny::TCPConnectionFailedForAllHosts)
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bunny-2.5.1/lib/bunny/session.rb:288:in `start'
	from bunny.rb:19:in `<main>'
W, [2016-09-14T17:54:48.648793 #16204]  WARN -- #<Bunny::Session:0x2fb4808 admin@myserver.com:5672, vhost=/, addresses=[myserver.com:5672]>: Could not establish TCP connection to myserver.com:5672: Bunny::ClientTimeout

This is the code I'm using:
@connection = Bunny.new(host:"myserver.com", port: 5672, user:"admin", pass:"xxxxxx")
@bunny_channel=@connection.start.create_channel
@exchange = @bunny_channel.topic("mytopic", :durable => true)

By using a webbrowser I can connect perfectly through the port 15672

Any idea why is this happening now?

**Comment by michaelklishin** [comment]
Please post questions to the mailing list.

The error message is fairly unambiguous. Successful connections on port 15672 in no way guarantee that port 5672 is open.

**Comment by michaelklishin** [comment]
[List of ports](http://www.rabbitmq.com/networking.html) used by various protocols supported or used by RabbitMQ is documented.

**Comment by MarioRuiz** [comment]
From the MQ admin:
![image](https://cloud.githubusercontent.com/assets/459564/18524409/cd7d4d76-7aa7-11e6-9b6b-e9356c75217e.png)
It is opened

**Comment by michaelklishin** [comment]
It just means that RabbitMQ is listening on it (on all interfaces). It doesn't mean that your firewall allows for inbound TCP connections on port 5672. You can easily check this by looking at the RabbitMQ log: all connections that send any data are logged (even if they are unsuccessful for one reason or another).

Again, please move this to the mailing list.
