### ISSUE TITLE
Memory Leak With RabbitMQ (3.2.4) and Bunny Gem (2.5.1) On Ruby. Ubuntu

### ISSUE THREAD

**Issue by l33z3r** [ruby-amqp/bunny#436]
Hi guys,

I am having a memory leak issue with RabbitMQ and bunny.
The workers memory usage constantly grows. 

I am on Ubuntu. 

Please see this Gist which replicates the issue: https://gist.github.com/l33z3r/6f783edc6258367d2ef9fa7c2402e666

Can somebody verify this please?

**Comment by michaelklishin** [comment]
You declare queues without ever cleaning them up.

**Comment by michaelklishin** [comment]
RabbitMQ questions belong to rabbitmq-users. 3.2.x isn't getting any more updates.

**Comment by l33z3r** [comment]
I am just illustrating that if I have a constantly running feed of messages, that there is a leak. I am planning on running the stream 24/7, and no matter what I try, the memory usage just constantly grows. It is not related to cleaning up the queues.

**Comment by michaelklishin** [comment]
@l33z3r this has been discussed to death on rabbitmq-users, e.g. [quite recently](https://groups.google.com/d/msg/rabbitmq-users/c0Pq4yEavmw/wiPHpbpICwAJ). Messages are supposed to be consumed. If they are not consumed then you probably want to use a database.

**Comment by michaelklishin** [comment]
On top of the above, your code [publishes messages as transient](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/channel.rb#L533) which means they will be kept in RAM for as long as possible (as defined by VM high memory watermark and disk paging ratio).
