### ISSUE TITLE
API reference link is broken

### ISSUE THREAD

**Issue by jkugler** [ruby-amqp/bunny#439]
This line https://github.com/ruby-amqp/bunny/blame/master/README.md#L150 links to http://reference.rubybunny.info/

This only links to the document, and not the API Reference, which is the first bug. However, once one is at the linked document, on the right side, there is a link to API Reference under section 8.3. This link is http://reference.rubybunny.info/#API_Reference

Clicking on that link takes you a section with a single link labeled "Bunny API Reference." However, this is simply a link to http://reference.rubybunny.info/

Where is the actual location for the API reference?

Thanks!

**Comment by michaelklishin** [comment]
[http://reference.rubybunny.info/](http://reference.rubybunny.info/) is the entire API reference. Have you tried the class and method lists in the upper right corner? That's how YARD generator works, it uses README as an index page (at least by default).

**Comment by michaelklishin** [comment]
A newer YARD version lists classes in a sidebar. Upgraded to it and redeployed.

**Comment by jkugler** [comment]
I don't see a class list in the upper right corner, but i do see the left side bar now. It's still a bit confusing that 8.3 is a link that goes to an empty section with a link that is back to the same document. :)

Thanks for the update!

**Comment by michaelklishin** [comment]
@jkugler there is only one README a repository can have and it must work for both Github and YARD. Sorry but it's an impassé.
