### ISSUE TITLE
Queue recovery attempts re-declaration with different properties

### ISSUE THREAD

**Issue by dopykuh** [ruby-amqp/bunny#445]
Hi,
We're running some functional tests with bunny and multiple rabbitmq servers.
The current situation described as the following: 
A daemon want to subscribe to a queue. These queue will be generated before with durable: true.
After subscribing to queue we're redeploying the amqp servers and the bunny recovery routine will recreacte the queue just with the default options.

**Comment by michaelklishin** [comment]
What does your code looks like? I need an example to reproduce. There are integration tests for recovery that use various topologies.

**Comment by michaelklishin** [comment]
Also, what are "the default options"?

**Comment by michaelklishin** [comment]
and what is in RabbitMQ logs?

**Comment by dopykuh** [comment]
The implementation is the following,

```ruby
          def subscribe(queue)
            @subscribe ||= {}
            @subscribe[queue] ||=
              begin
                queue, options = transport.parse_queue(queue)
                q = channel.queue(queue_with_variables(default_queue: queue),
                                  options.to_h.symbolize_keys)
                q.subscribe(manual_ack: true) do |info, _properties, payload|
                  logger.debug("Received #{payload}"\
                               " from #{queue}")
                  begin
                    j = Job::Meta.register(job: payload,
                                           transport: 'Bunny')
                    logger.debug "Registed job #{j.gibber_id}"
                    redis.lpush router.routing_queue, Oj.dump(j.attributes)
                    router.notify! rescue nil
                    channel.ack(info.delivery_tag, false)
                  rescue => e
                    channel.reject(info.delivery_tag, true) rescue nil
                    redis.reconnect rescue nil
                    logger.error 'Invalid message fetched.'\
                      ' Prevent from fail, logging exception...'
                    logger.error e
                  end
                end
              rescue Exception::Transport::ChannelError => e
                logger.error e
                sleep 0.2
                retry
              end
          end
```

**Comment by dopykuh** [comment]
The queue recovery happens here?
https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/queue.rb#L370

**Comment by michaelklishin** [comment]
What do `queue_with_variables(default_queue: queue)` and `options.to_h.symbolize_keys` return?

There are two known issues with recovery but it has been around for years, has automated tests and I highly doubt that entities can be re-declared with different properties. *Different* objects could be declared concurrently, perhaps, but that's not entirely a library responsibility to avoid that.

**Comment by michaelklishin** [comment]
Queue recovery [beings in Bunny::Channel#recover_queues](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/channel.rb#L1528).

**Comment by michaelklishin** [comment]
Individual queue recovery starts in [`Bunny::Queue#recover_from_network_failure`](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/queue.rb#L333).

We still have effectively zero information useful to create a reproducing case. What is in RabbitMQ log? what exactly do your library's helper functions pass to `Bunny::Channel#queue`?

**Comment by dopykuh** [comment]
We're currently also not able to reproduce them. 
I only serve "durable: true" to Bunny::Channel#queue.

There are multiple tests on my side which raise a network failure by using iptables and the recovery happens as expected. But it looks like, if the queue went away it would be incorrectly redeclared.

**Comment by dopykuh** [comment]
> Queue recovery beings in Bunny::Channel#recover_queues.
Possibly a deep dup required here?

**Comment by michaelklishin** [comment]
@dopykuh let's spare ourselves some time and stop guessing. Please post server logs and specific values passed to `Bunny::Channel#queue`.

**Comment by michaelklishin** [comment]
`Bunny::Channel#recover_queues` already duplicates queue hash values. We do not want to duplicate queue objects there and even if we did so, queues un- and re-register themselves as soon as they are redeclared and their new (or unchanged) name is known. So what would that accomplish other than creating a bunch of soon-to-be-collected objects?

I'm going to add synchronization there as part of #407 but I fail to see how a "deep dup" on a string => `Bunny::Queue` map would do anything.

**Comment by dopykuh** [comment]
Shame on me, fail on my side. Thanks a lot for the fast feedback ;)

**Comment by michaelklishin** [comment]
@dopykuh no worries. I'm still not sure what it was but synchronized the queues collection as promised in master :)

**Comment by dopykuh** [comment]
All happens as expected, take a look at my routine. 
After joining the method i redeclared the variable queue. 
So if an exception occured the retry doesn't get the same objects. ;)

**Comment by michaelklishin** [comment]
Ah, ok, thank you for reporting back and clarifying!

**Comment by dopykuh** [comment]
Best support for biggest noobs :smile:
