### ISSUE TITLE
Raise timeout with rails

### ISSUE THREAD

**Issue by keepcosmos** [ruby-amqp/bunny#449]
I put code in after fork block (and also try in initialize file)

```ruby
$rabbitmq = Bunny.new(ENV['xxx'])
$rabbitmq.start
$channel = rabbitmq.create_channel
```

After that I opened console `rails console` and I tried to make queue, or create other channel, but it raised Timeout error.

```ruby
> channel = $rabbitmq.create_channel
#or
> queue = $channel.queue("xx")
```

```
Timeout::Error: Timeout::Error
from /home/vagrant/.rvm/gems/ruby-2.2.3/gems/bunny-2.6.1/lib/bunny/concurrent/continuation_queue.rb:33:in `block in poll'
```
 
Did I miss something?

**Comment by michaelklishin** [comment]
I don't know what value `ENV['xxx']` has or what `rails console` does atop `irb` but Bunny can be used from the REPL (and I do so extensively). Please consider posting questions to the mailing list.
