### ISSUE TITLE
Question: proper use of channels/exchanges 

### ISSUE THREAD

**Issue by blanchma** [ruby-amqp/bunny#451]
I read the documentation a thousands times but I'm not sure yet of what I should do in a case I have a heavy use of publishing messages.

Re-use the exchange? Re-use the channel? Or create a channel/exchange and then close the channel after publish?

Thanks in advance

**Comment by michaelklishin** [comment]
Questions belong to the mailing list. Opening a channel and declaring an exchange us a network roundtrip. Connections, channels, exchanges are typically long lived. In your specific example, does introducing 2 network roundtrips per message with a protocol that intentionally doesn’t have a synchronous response for basic.publish sound optimal? Not to me.

**Comment by michaelklishin** [comment]
In fact, every channel object in Bunny maintains a cache of queues and exchanges (objects), so previously declared and not deleted by Bunny exchanges won't result in a network roundtrip. It is
a way to avoid them when DSL lovers copy tutorial examples and put them in a tight loop.

**Comment by blanchma** [comment]
Thanks, my approach is using a ConnectionPool to keep some channels and share them between different jobs that publish messages. 

But this:

ch = conn.create_channel(nil, 16)

From http://rubybunny.info/articles/concurrency.html#sharing_channels_between_threads <http://rubybunny.info/articles/concurrency.html#sharing_channels_between_threads> is the confusing part.  If channel already have a pool, I can create one and share between jobs.

**Comment by michaelklishin** [comment]
Channels are not pooled by Bunny and the docs explain why this is a particularly bad idea for publishing.

**Comment by blanchma** [comment]
So keeping my own pool is a good idea.

**Comment by michaelklishin** [comment]
Ahem. No, it is a terrible idea: you will be sharing channels
between threads for publishing which 
the docs quite explicitly call out to be unsupported.
Pooling is much harder to get right than it seems, too.

**Comment by blanchma** [comment]
So, I can’t share them so I should trust in Bunny caching of exchange and channels and create a channel every time I need it and then close it?

**Comment by michaelklishin** [comment]
@blanchma this is too long to be in an issue.

Connections and channels are typically long lived. Channels can be closed due to recoverable errors and then apps must open a new one. Sharing channels among threads for publishing is a no-no, as explained in the docs. Opening a channel for every message adds very substantial overhead and is completely unnecessary.

`Bunny::Channel#exchange`, `Bunny::Channel#topic` and other helpers maintain an object cache of `Bunny::Exchange` objects and won't attempt to redeclare over and over.

I don't have much to add.
