### ISSUE TITLE
x-message-ttl not doing nothing 

### ISSUE THREAD

**Issue by blanchma** [ruby-amqp/bunny#452]
When I declare a queue I use:

`queue = @channel.queue(@queue_name, durable: true, arguments: {"x-message-ttl" => 15000 })`

to set a Per Queue Message TTL as in the docs but nothing happen. Only if I a set a policy is working. I'm using CloudAMQP as a service. Ruby 2.3.1 and Buny 2.6.2. Any clues? Thanks

**Comment by michaelklishin** [comment]
I cannot reproduce. Most likely you get a channel exception (which should be quite visible even without server logs, though) because existing queue arguments do not match those provided.

Nothing has changed in `queue.declare` or optional argument table implementation in years.
