### ISSUE TITLE
Raw timestamp value

### ISSUE THREAD

**Issue by carlhoerberg** [ruby-amqp/bunny#455]
Some producers (eg. the events-exchange) produces timestamp in ms not in seconds, but the Bunny library parses the value to a DateTime thinking the value is always in seconds. So it would be good if there was a way to extract the timestamp's raw value in addition to the automatically parsed one.

**Comment by michaelklishin** [comment]
What would that look like? The spec requires second-level precision and all alternatives use optional headers.

**Comment by carlhoerberg** [comment]
Just another property, like `headers.timestamp_raw` where the value isn't parsed to a `DateTime`. Source of problem can be things like: https://github.com/rabbitmq/rabbitmq-event-exchange/issues/8

**Comment by michaelklishin** [comment]
`Bunny:: MessageProperties#raw_timestamp` sounds good. We can also add `Bunny:: MessageProperties#timestamp_in_ms`.

**Comment by carlhoerberg** [comment]
Seems to be done at two places: 
https://github.com/ruby-amqp/amq-protocol/blob/c292d823fb48750531ed2e601ce966ca3a8d4763/lib/amq/protocol/table_value_decoder.rb#L138
https://github.com/ruby-amqp/amq-protocol/blob/c292d823fb48750531ed2e601ce966ca3a8d4763/codegen/protocol.rb.pytemplate#L214

What do you think is the best way to handle that? Keep the value as an `Integer` all the way up, and let this project parse it instead? I guess it could break other libraries that uses `amq-protocol`..

**Comment by michaelklishin** [comment]
I'd rather not change `amq-protocol`. `timestamp_high_res` in `event-exchange` uses a numerical value, not the AMQP 0-9-1 timestamp type.

**Comment by fbbergamo** [comment]
Is there any alternative to have the timestamp in ms?

**Comment by michaelklishin** [comment]
@fbbergamo I cannot think of any that do not involve forking every client library you use. Use message headers. They are extensible for a reason.

**Comment by carlhoerberg** [comment]
Proper handling of the timestamp property (64 uint) was fixed in ruby-amqp/amq-protocol#65. So now you can use `headers.timestamp.to_i` to get the proper ms value.

**Comment by fbbergamo** [comment]
@carlhoerberg 
Do you know if `headers.timestamp.to_f` will work as well?

**Comment by michaelklishin** [comment]
@fbbergamo why don't you do a little experiment? Even if it doesn't, `headers.timestamp.to_i.to_f` should.
