### ISSUE TITLE
How can I make use of amq.rabbitmq.reply-to in a multi-threaded environment?

### ISSUE THREAD

**Issue by nuc** [ruby-amqp/bunny#461]
Hello there,

I'm trying to make use the direct reply-to channel, but I'm having troubles to make it work in a multi-threaded environment (sidekiq).

My approach is the following:

- Create a channel per thread and store it under `Thread.current`.
- Subscribe to `amq.rabbitmq.reply-to` once before publishing any message.
- Store a `callbacks` hash under current thread and allow clients to add callbacks.
- When a reply is received, call the matching callback based on correlation id.

The problem is that `channel.queue.subscribe` will run the passed block under a different thread. 

That makes it impossible to identify the matching callback that needs to be called.

That's roughly the code:

```ruby
class ReplyQueue

  REPLY_QUEUE_LOCK ||= Monitor.new

  def subscribe(&callback)
    setup_reply_queue_if_needed
    callback_uuid = SecureRandom.uuid
    @callbacks ||= {}
    @callbacks[callback_uuid] = callback
    callback_uuid
  end

  def name
    'amq.rabbitmq.reply-to'
  end

  private

  def setup_reply_queue_if_needed
    REPLY_QUEUE_LOCK.synchronize do
      unless Thread.current[:reply_queue]
        channel = Connection.reusable_channel # That's a channel stored in as a thread var
        reply_queue = channel.queue(name, no_ack: true)
        reply_queue.subscribe do |delivery_info, properties, payload|
          handle_message(delivery_info, properties, payload)
        end
        Thread.current[:reply_queue] = reply_queue
      end
    end
  end

  def handle_message(*args)
    # Callbacks are missing, since that runs in a new thread
    callbacks.each {|callback_uuid, callback| callback.call(*args) }
  end
end

module Producer
  extend self

  def publish(object_type, options={}, &block)
    channel = Connection.reusable_channel # That's a channel stored in as a thread var
    exchange = channel.fanout('posts')

    lock = Mutex.new
    condition = ConditionVariable.new
    correlation_id = SecureRandom.uuid

    reply_queue = ReplyQueue.new
    callback_uuid = reply_queue.subscribe do |delivery_info, properties, payload|
      if properties[:correlation_id] == correlation_id
        lock.synchronize{condition.signal}
      end
    end

    exchange.publish(options[:payload],
      :content_type   => 'application/json',
      :correlation_id => correlation_id,
      :reply_to       => reply_queue.name)

    lock.synchronize{condition.wait(lock)}
    reply_queue.unsubscribe(callback_uuid)
  end
end
```

I guess a way to make it work would be to share the callbacks between all threads, but that sounds scary.

Any ideas of how could I make it work, in a non-scary way?

Thanks :)

**Comment by michaelklishin** [comment]
Bunny has a mailing list.

**Comment by michaelklishin** [comment]
`@callbacks` in your code is shared mutable state. It might be more straightforward to run a number of those request/reply servers (as in [tutorial 6](http://www.rabbitmq.com/getstarted.html)) each in its own thread and eliminate the "shared" aspect.

**Comment by nuc** [comment]
Yeah, you are right about the callbacks, I pasted the wrong code version while trying out things, but you got the point.

The only problem with the RPC tutorial is that you can't do something like this:

```ruby
client = FibonacciClient.new(ch, "rpc_queue")
client.call(30)
client.call(50)
```
Second `client.call` will throw a `PRECONDITION_FAILED - reply consumer already set (Bunny::PreconditionFailed)`, because you can't have more than one subscribers to `amq.rabbitmq.reply-to` per channel. And if I understood it correctly, there is no `unsubscribe` anymore in bunny.

But thanks anyway, I will move the discussion to the mailing list.

Cheers

**Comment by michaelklishin** [comment]
That tutorial is just an example. Even so, you can do

``` ruby
c1 = FibonacciClient.new(ch, "rpc_queue")
c1.call(30)

c2 = FibonacciClient.new(ch, "rpc_queue")
c2.call(30)
```

with one client per thread (and using its own channel, which is where all Direct Reply-to state is stored).

**Comment by nuc** [comment]
Yeah, probably I'll move to this direction.

Thanks again 👍
