### ISSUE TITLE
Sporadic failures during channel recovery

### ISSUE THREAD

**Issue by jhtwong** [ruby-amqp/bunny#490]
I've spent a few days trying to make my app handle catastrophic failures of the broker, and noticed that channel recovery sometimes doesn't work out. When that happens, publishing messages on that channel results in the messages going nowhere (and yet no exceptions are raised either). (And no, I'm not using publisher confirms yet.)

Whenever the trouble happens, this is what I see in the logs...

```
D, [2017-03-09T13:38:21.908003 #61744] DEBUG -- : Recovering channel 1 after network failure
D, [2017-03-09T13:38:21.908114 #61744] DEBUG -- : Recovering queue foobar
D, [2017-03-09T13:38:21.910656 #61744] DEBUG -- : Session#handle_frame on 0: #<AMQ::Protocol::Connection::Close:0x007fbbe52a9998 @reply_code=504, @reply_text="CHANNEL_ERROR - expected 'channel.open'", @class_id=50, @method_id=10>
W, [2017-03-09T13:38:21.910758 #61744]  WARN -- : Recovering from connection.close (CHANNEL_ERROR - expected 'channel.open')
D, [2017-03-09T13:38:22.466712 #61744] DEBUG -- : Will attempt connection recovery...
```

Not sure if this is something that I could work around, or if this is a race condition bug somewhere in the stack...

**Comment by michaelklishin** [comment]
I can't suggest anything with the amount of information provided.

**Comment by michaelklishin** [comment]
Automatic connection recovery in Bunny does not cover published messages. If you are not using publisher confirms, there are no guarantees.

**Comment by jhtwong** [comment]
I actually implemented queuing myself, and before every publish attempt to do a `session.start` if it's not `open?` as well as attempt `session.handle_network_failure(e)` if that fails... and all in a loop until the connection and channel comes back...

**Comment by michaelklishin** [comment]
`Bunny::Session#handle_network_failure` is not supposed to be called by user code. You are causing two parallel recoveries.
