### ISSUE TITLE
Is there any recommended way to share connection in threaded server such as puma?

### ISSUE THREAD

**Issue by mz026** [ruby-amqp/bunny#494]
I tried to setup bunny connection following [the doc](http://rubybunny.info/articles/connecting.html#connecting_in_web_applications_ruby_on_rails_sinatra_etc), but in puma's `after_worker_boot` callback. But when I tried to create a channel I got a `Timeout::Error` like this:

```
Timeout::Error (Timeout::Error):
  bunny (2.2.2) lib/bunny/concurrent/continuation_queue.rb:33:in `block in poll'
  bunny (2.2.2) lib/bunny/concurrent/continuation_queue.rb:30:in `synchronize'
  bunny (2.2.2) lib/bunny/concurrent/continuation_queue.rb:30:in `poll'
  bunny (2.2.2) lib/bunny/session.rb:1211:in `wait_on_continuations'
  bunny (2.2.2) lib/bunny/session.rb:498:in `open_channel'
  bunny (2.2.2) lib/bunny/channel.rb:220:in `open'
  bunny (2.2.2) lib/bunny/session.rb:341:in `block in create_channel'
```

Is there any recommended way to set up Bunny in threaded server like puma?
Thanks in advanced!

**Comment by michaelklishin** [comment]
Questions belong to the mailing list. [There is a concurrency guide](http://rubybunny.info/articles/concurrency.html) it's impossible to recommend anything with the amount of information provided.
