### ISSUE TITLE
Session#start doesn't seem to be thread safe

### ISSUE THREAD

**Issue by kevindew** [ruby-amqp/bunny#498]
We've been running into problems for a while of intermittent errors with Bunny of `NoMethodError: undefined method `next_channel_id' for nil:NilClass` which seem to be when somehow the [channel_id_allocator](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L1177) is nil

We've been trying to work out what's going on and I think I've traced the issue back to the fact that [we're running connection.start on threads](https://github.com/alphagov/publishing-api/blob/master/lib/queue_publisher.rb#L12) and it's possible that this gets called at the same time which seems to cause the issue. If I put this in a mutex it seems to resolve our issue.

In some isolated tests I can see it happening (and some other issues):
```
[1] pry(main)> config = Rails.application.config_for(:rabbitmq).symbolize_keys; conn = Bunny.new(config.except(:exchange)); thread_1 = Thread.new { conn.start.create_channel }; thread_2 = Thread.new { conn.start.create_channel }; thread_1.join; thread_2.join;
NoMethodError: undefined method `next_channel_id' for nil:NilClass
from /usr/lib/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bunny-2.5.1/lib/bunny/session.rb:871:in `next_channel_id'
```

```
[1] pry(main)> config = Rails.application.config_for(:rabbitmq).symbolize_keys; conn = Bunny.new(config.except(:exchange)); thread_1 = Thread.new { conn.start.create_channel }; thread_2 = Thread.new { conn.start.create_channel }; thread_1.join; thread_2.join;
Bunny::NoFinalOctetError: Frame doesn't end with � as it must, which means the size is miscalculated.
from /usr/lib/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bunny-2.5.1/lib/bunny/transport.rb:255:in `read_next_frame'
```

```
[1] pry(main)> config = Rails.application.config_for(:rabbitmq).symbolize_keys; conn = Bunny.new(config.except(:exchange)); thread_1 = Thread.new { conn.start.create_channel }; thread_2 = Thread.new { conn.start.create_channel }; thread_1.join; thread_2.join;
E, [2017-04-19T21:07:46.935963 #29285] ERROR -- #<Bunny::Session:0x7f73b1eb4e58 publishing_api@localhost:5672, vhost=/, addresses=[localhost:5672]>: Got an exception when receiving data: Connection reset by peer (Errno::ECONNRESET)
W, [2017-04-19T21:07:46.936202 #29285]  WARN -- #<Bunny::Session:0x7f73b1eb4e58 publishing_api@localhost:5672, vhost=/, addresses=[localhost:5672]>: An empty frame was received while opening the connection. In RabbitMQ <= 3.1 this could mean an authentication issue.
E, [2017-04-19T21:07:46.937133 #29285] ERROR -- #<Bunny::Session:0x7f73b1eb4e58 publishing_api@localhost:5672, vhost=/, addresses=[localhost:5672]>: Got an exception when receiving data: closed stream (IOError)
IOError: closed stream
from /usr/lib/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bunny-2.5.1/lib/bunny/cruby/socket.rb:49:in `select'
```

I figure it might be just that this method isn't meant to be threadsafe, but thought I'd post it up in case it was an issue since it's been bugging us for a while.

**Comment by michaelklishin** [comment]
`NoMethodError: undefined method `next_channel_id' for nil:NilClass` means that `Bunny::Session#start` was never invoked.

I see no problem with the state of things as they are. Most apps do not share connections between threads, those that do should at least take care of opening it first. A `Mutex#synchronize` around connection initialization is easy enough to add.
