### ISSUE TITLE
undefined method `next_channel_id' for nil:NilClass

### ISSUE THREAD

**Issue by gjack** [ruby-amqp/bunny#504]
We're using bunny 2.2.2 and getting a significant number of errors (undefined method `next_channel_id' for nil:NilClass) when creating a new channel. Is there a way to prevent these or a fix?

**Comment by michaelklishin** [comment]
@gjack consider reporting full stack traces when seeking help.

In 99% of cases that exception means that you did not invoke `Bunny::Session#start` after instantiating it with `Bunny.new`.

**Comment by michaelklishin** [comment]
Also consider posting questions to the mailing list in the future.

**Comment by michaelklishin** [comment]
Lastly, the most recent Bunny release is 2.7.0 which is a couple of dozens of releases ahead of 2.2.2. Wink wing, nudge nudge.

**Comment by zhubert** [comment]
@michaelklishin I understand that the mailing list is the best way to get answers to questions, however, do you feel that your tone is the best way to promote an inclusive community for this project?

**Comment by michaelklishin** [comment]
@zhubert when people are asking for my time I expect a reasonable amount of information provided, regardless of their gender, race, and so on. So I don't pretend to be a nice guy but in this issue specifically my tone is reasonable.

**Comment by michaelklishin** [comment]
As if 1c117c58abd7150dfaf69497937e37b14a7e61fe the exception is a bit clearer.
