### ISSUE TITLE
Connectivity issues when connecting

### ISSUE THREAD

**Issue by jgrau** [ruby-amqp/bunny#505]
We use [`sneakers`](https://github.com/jondot/sneakers/) which in turn uses `bunny` so my apologies if this issue is with `sneakers` and not with `bunny`. I've also [opened the issue in the `sneakers` issue tracker](https://github.com/jondot/sneakers/issues/291).

We are hosted on Heroku and use CloudAMQP. I am trying to debug an issue we see on every deploy/restart of our workers. The workers fail to connect to rabbitmq for up to 20 minutes then suddenly connects correctly. I have been working with CloudAMQP and Heroku support on this and received the following thorough response from Heroku:

> Hi Jonas,

> Networking is available immediately at Dyno boot, including DNS resolution. I can reproduce this issue consistently, your app doesn't connect to CloudAMQP for the first ~15-20 minutes of it's execution. Afterwards, it appears to connect, or at least the error messages stop spewing to your log stream every ~2 seconds.

> My gut feeling is that something else is at play with either Sneakers or Bunny, but the extent of my research so far has not turned anything up. This ticket is remaining open while I discuss it with colleagues but I did want to acknowledge that we see the issue as well, and that I don't have any solution. Nothing at the platform level is preventing this connection from taking place, but I'll see what I can do to determine why these connection errors are occurring.

> I did look at what I expected to be standard configuration files (config/initializers/sneakers.rb) but didn't see anything obvious to do with host connections as opposed to message / queue specific configuration. Is there a connection timeout or other related option you can increase to see if the connection attempt is just over-eager?

> Thanks!
> Jason

> Jonas,

> I ran some further tests with an engineer and we're confident this is a library issue of some sort. While the rake sneakers:run task continues to fail, tools that establish a host level connection with the destination host connects without an issue. This may point to an overly stringent timeout, authentication issues, or something else of the sort:

```
$ nc -w5 -vz hare.rmq.cloudamqp.com 5672
Connection to hare.rmq.cloudamqp.com 5672 port [tcp/amqp] succeeded!
Via netcat (nc), we can make a TCP connection to CloudAMQP's endpoint without issue.
```

> Immediately after, or even during this attempt, your application's connection process fails:

```
$ bundle exec rake sneakers:run
2017-05-26T17:33:44Z p-2158 t-os66erfyg WARN: Loading runner configuration...
2017-05-26T17:33:44Z p-2158 t-os66erfyg WARN: Loading runner configuration...
2017-05-26T17:33:44Z p-2158 t-os66erfyg WARN: Loading runner configuration...
2017-05-26T17:33:44Z p-2161 t-os66erfyg WARN: Could not establish TCP connection to hare.rmq.cloudamqp.com:5672: No route to host - connect(2) for 52.19.224.195:5672
Unexpected error Could not establish TCP connection to any of the configured hosts
```

> As I previously suggested, please look into connection, authentication, or subscription timeouts. Something seems over-aggressive in giving up before the entire process is allowed to take place.

> Let me know if you have any further questions.

> Thanks!
Jason

My config:

```
require 'sneakers'
require 'sneakers/handlers/maxretry'
require 'sneakers_sentry_reporter.rb'

# Require all our workers. This is required for sneakers
# to know which queues and bindings to set up
Dir[Rails.root.join('app', 'workers', '*.rb')].each do |file|
  require file
end

config = {
  amqp: ENV['CLOUDAMQP_URL'] || 'amqp://guest:guest@localhost:5672',
  handler: Sneakers::Handlers::Maxretry,
  daemonize: false,
  workers: 1,
  threads: 1,
  prefetch: 1,
  share_threads: true,
  connection: Rails.env.test? ? BunnyMock.new.start : nil,
  error_reporters: [SneakersSentryReporter.new],
  exchange_type: :topic
}

Sneakers.configure(config)
Sneakers.logger.level = Logger::WARN
```

I realize that this is probably not directly a sneakers or bunny issue so I guess it's more of a question about whether this rings any bells or whether someone knows of an aggressive timeout being set.

**Comment by michaelklishin** [comment]
Please use Bunny (or RabbitMQ) mailing list for questions in the future.

tcp dump and [Wireshark](http://www.rabbitmq.com/amqp-wireshark.html) will provide you a lot of the data to work with but

> No route to host

strongly suggests a hostname resolution problem.

DNS timeouts in minutes are definitely not unheard of and it is a common enough issue e.g. in local developer environments where VPN is used.

Why a Ruby process would resolve hostname differently from netcat, I don't know.

**Comment by michaelklishin** [comment]
Wrote an answer, then noticed the `No route to host` message, then edited it to be confusing. Should be corrected now. Hostname resolution and/or routing are things I'd recommend investigating (e.g. try `dig` and `traceroute`).
