### ISSUE TITLE
Creating Shovel

### ISSUE THREAD

**Issue by edwinlunando** [ruby-amqp/bunny#506]
Hi, I would like to create https://www.rabbitmq.com/shovel-dynamic.html programmaticaly. Could I achieve it by using bunny?

**Comment by michaelklishin** [comment]
Please post questions to the mailing list.

Bunny is an AMQP 0-9-1 client. rabbitmq-shovel is not a part of the protocol. See [rabbitmq-shovel-management](https://github.com/rabbitmq/rabbitmq-shovel-management) and the [HTTP API](http://www.rabbitmq.com/management.html) extensions it provides.
