### ISSUE TITLE
Include unacknowledged messages in Bunny::Queue#message_count

### ISSUE THREAD

**Issue by Aminekanane** [ruby-amqp/bunny#507]
Hello, i'am unable to retrieve unacknowledged messages from a queue using Bunny, i need this number in order to perform automatic scaling down actions on several containers(Consumers). I can't see how i can do it using only Bunny. The API of RAbbitMQ can be usefiull, but i would like to do this with Bunny,
Thank You guys.

**Comment by carlhoerberg** [comment]
The AMQP protocol does not make that information available. Use the
RabbitMQ​ mgmt HTTP API.

**Comment by michaelklishin** [comment]
@Aminekanane see [RabbitMQ HTTP API client for Ruby](https://github.com/ruby-amqp/rabbitmq_http_api_client).
