### ISSUE TITLE
NoMethodError: undefined method `queue' for #<AMQ::Protocol::Exchange::DeclareOk:0x000000038b1ac0>

### ISSUE THREAD

**Issue by dipayan16** [ruby-amqp/bunny#508]
Getting this error everything I am calling bind method.
`queue= Bunny::Queue.new(bunny_client, queue_name, {:durable=>true})

 bind_res = queue.bind(exchange,{:routing_key=>queue.name})
`

**Comment by michaelklishin** [comment]
See #386, #192, #188.

**Comment by michaelklishin** [comment]
…as well as [Concurrency Considerations](http://rubybunny.info/articles/concurrency.html) in the docs.

Without seeing more of your code there's one more thing that catches the eye: `Bunny::Queue` is not really meant to be instantiated directly. Use `Bunny::Channel#queue`, as in documentation guides.

**Comment by dipayan16** [comment]
Thank you :)
