### ISSUE TITLE
Getting Bunny::ConnectionClosedError even though my bunny client status is :open

### ISSUE THREAD

**Issue by dipayan16** [ruby-amqp/bunny#509]
Every now and then before doing a pop from the queue I am getting the following error message : 
**Trying to send frame through a closed connection. Frame is #<AMQ::Protocol::MethodFrame:0x00000002f3bf90 @payload=\"\\x002\\x00\\n\\x00\\x00,adlandpro_com_newclassifieds_geebo_rss_queue\\x03\\x00\\x00\\x00\\x00\", @channel=1>, method class is AMQ::Protocol::Queue::Declare**

To debug further, I logged the status of bunny client using bunny_client.status which shows **:open** at that point of time. Can someone provide some insight in that?

This is how I am creating the bunny client:

```
$sdf_queue_global_connection_pool ||= {}

global_connection_key= args_hash[:rabbitmq_host].to_s + args_hash[:port].to_s + @vhost.to_s

bunny_client=$sdf_queue_global_connection_pool[global_connection_key]
                        if not bunny_client or bunny_client.status != :open
                                bunny_client=Bunny.new({:host=>args_hash[:rabbitmq_host], :port => args_hash[:port], :vhost => @vhost, :continuation_timeout => 8000})
                                $sdf_queue_global_connection_pool[global_connection_key]=bunny_client
                        end
                       
                        bunny_client.start
                        if not channnel or not channnel.status == :open
                                #Refence : http://reference.rubybunny.info/Bunny/Channel.html
                                channnel = bunny_client.create_channel
                              
                        end
                        raise Exception.new("Could not allocate channnel id") if not channnel
                        $log.info "Successfully created channal id #{channnel.id} for bunny client"

                        queue_config = channnel.queue(@queue_name,{:durable=>true})
                        exchange=channnel.exchange(exchange_name,{:key=>default_exchange_key,:durable=>exchange_durable,:type=>exchange_type})
                        bind_res = queue_config.bind(exchange,{:routing_key=>queue_config.name})`

**Comment by michaelklishin** [comment]
Please post questions to the mailing list.

The exception is unambiguous: at a point in time, Bunny connection (a `Bunny::Session` instance) was closed when a `queue.declare` method was used (`Bunny::Channel#queue` in the snippet above). Correlating this to server logs will help identify why.

**Comment by dipayan16** [comment]
Thanks for your reply.  I understand the situation. But what is strange is at that time Bunny connection status showing 'open', which should return 'close'. Isn't it? Please help here.

**Comment by michaelklishin** [comment]
@dipayan16 there's little I can help with without a way to reproduce this at least some of the time. You can export `BUNNY_LOG_LEVEL=debug` or set log level to `:debug` for a connection to make Bunny print every single frame that it handles (that's a lot of output). Such log combined with [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) will help you figure out what is going on. There are only few places where connection state variable is updated, you can add extra logging there.

**Comment by dipayan16** [comment]
@michaelklishin  Thanks for the quick response! I will try to place the things similarly.
