### ISSUE TITLE
Issue with subscriber for Topic exchange

### ISSUE THREAD

**Issue by dipayan16** [ruby-amqp/bunny#510]
Hi,
There is some strange thing happening with topic exchange. When I'm publishing messages in the queue with different routing key its working fine. However, the during subscription with the same routing key is coming empty. Can you tell where I am doing the mistake?

Publisher code : 

```conn = Bunny.new
conn.start
channel       = conn.create_channel
queue = channel.queue("crawl.end.time.test",{:durable=>true})
exchange = channel.topic("Queue_test")
bind = queue.bind(exchange,:routing_key => "crawl.end.time.test.#")




exchange.publish("Testing_urls1", :routing_key => "crawl.end.time.test.123456")
exchange.publish("Testing_urls2", :routing_key => "crawl.end.time.test.123456")
exchange.publish("Testing_urls3", :routing_key => "crawl.end.time.test.12345")
exchange.publish("Testing_urls4", :routing_key => "crawl.end.time.test.956412")
```

My queue content is looking like:
+----------------------------+----------+---------------+---------------+---------------+------------------+-------------+
|        routing_key         | exchange | message_count |    payload    | payload_bytes | payload_encoding | redelivered |
+----------------------------+----------+---------------+---------------+---------------+------------------+-------------+
| crawl.end.time.test.123456 | Queue_test  | 3             | Testing_urls1 | 13            | string           | True        |
| crawl.end.time.test.123456 | Queue_test  | 2             | Testing_urls2 | 13            | string           | True        |
| crawl.end.time.test.12345  | Queue_test  | 1             | Testing_urls3 | 13            | string           | True        |
| crawl.end.time.test.956412 | Queue_test  | 0             | Testing_urls4 | 13            | string           | True        |
+----------------------------+----------+---------------+---------------+---------------+------------------+-------------+

Subscriber code: 

``` result = []
channel.queue("craw.end.time.test").bind(exchange,:routing_key => "#.956412").subscribe do |delivery_info, properties, payload|
result << payload
end```

result is showing []

**Comment by dipayan16** [comment]
Update: 
Used 

```queue = channel.queue("crawl.end.time.test",{:durable=>true})
sub = queue.bind(exchange,:routing_key => "#.956412")
sub.subscribe do |delivery_info, properties, payload|
result << payload
end
```

2.2.4 :018 > result
 => ["Testing_urls1", "Testing_urls2", "Testing_urls3", "Testing_urls4"] 
 Why its giving payload of all the routing keys?

**Comment by michaelklishin** [comment]
Please use mailing list for questions. I asked for that a few times before.

**Comment by michaelklishin** [comment]
When multiple queues are bound to a topic exchange with the same routing key pattern and a message matches it, a copy of the message will be routed to each queue regardless of the payload.

Modifying a local variable/collection from a `Bunny::Queue#subscribe` won't lead you to predictable results because it is invoked asynchronously. If the goal is to "batch" delivery processing, sounds like you want an  [concurrent collection](https://github.com/ruby-concurrency/concurrent-ruby) of some kind.
