### ISSUE TITLE
Undefined method `message_count' for #<AMQ::Protocol::Basic::ConsumeOk>

### ISSUE THREAD

**Issue by sullerandras** [ruby-amqp/bunny#514]
On application startup we occasionally get `undefined method 'message_count'` error when calling `queue.message_count` in the `subscribe` block.
This only happens when there are messages in the queue when the application starts, I never saw the error when the queue was empty.
The error never happens when the application is already running, only on startup.
The application is single threaded.

Any idea why this is happening?

bunny 2.7.0
rabbitmq 3.6.9
ruby 2.4.1
Mac OS X 10.11.6 (dev machines) and also Linux in Docker (servers)

## How to reproduce

Create a queue and publish a message to it:
```bash
rabbitmqadmin declare exchange name=testing type=topic auto_delete=false durable=false
rabbitmqadmin declare queue name=testing_queue auto_delete=false durable=false
rabbitmqadmin declare binding source=testing destination=testing_queue routing_key=test
rabbitmqadmin publish routing_key=test exchange=testing payload=aaa
```

Run this script with `ruby script.rb`:
```ruby
require 'bunny'

conn = Bunny.new
conn.start

channel = conn.create_channel
queue = channel.queue('testing_queue', exclusive: false, durable: false, auto_delete: false)
queue.subscribe(manual_ack: true) do |deliver_info, metadata, payload|
  puts "======> received"
  puts "remaining messages: #{queue.message_count}" # this line throws error sometimes
end
sleep 0.1
```

To run it hundred times with bash:
```bash
for i in {1..100}; do echo "===> i: $i"; ruby script.rb ; echo $? ; done
```

I get errors like this about 20% of the time:
```
E, [2017-07-31T16:02:16.765067 #4051] ERROR -- #<Bunny::Session:0x7ff29a1b5c08 guest@127.0.0.1:5672, vhost=/, addresses=[127.0.0.1:5672]>: Uncaught exception from consumer #<Bunny::Consumer:70339972115020 @channel_id=1 @queue=testing_queue> @consumer_tag=bunny-1501488136000-946326484150>: #<NoMethodError: undefined method `message_count' for #<AMQ::Protocol::Basic::ConsumeOk:0x007ff29a1a4750>> @ /Users/andras/.rvm/gems/ruby-2.4.1@my_gemset/gems/bunny-2.7.0/lib/bunny/queue.rb:312:in `status'
/Users/andras/.rvm/gems/ruby-2.4.1@my_gemset/gems/bunny-2.7.0/lib/bunny/channel.rb:935:in `basic_consume_with': undefined method `consumer_tag' for #<AMQ::Protocol::Queue::DeclareOk:0x007ff29a1973e8> (NoMethodError)
Did you mean?  consumer_count
	from /Users/andras/.rvm/gems/ruby-2.4.1@my_gemset/gems/bunny-2.7.0/lib/bunny/queue.rb:192:in `subscribe'
	from script.rb:8:in `<main>'
```

**Comment by michaelklishin** [comment]
It's a race condition between two protocol methods.

See #508, #386, #192, #188.

**Comment by michaelklishin** [comment]
If you really need to invoke `Bunny::Queue#message_count` (or anything else that does a `queue.declare` on the same queue you are consuming from), do it on a separate channel. Or just don't do it at all.

Current continuation implementation cannot differentiate between two responses for two pending operations. There are no plans to change it because all client libraries use the same approach and it is really easy to reason about (and works great in most scenarios).

Java client recent introduced [a way to ignore out of order continuation responses](https://github.com/rabbitmq/rabbitmq-java-client/issues/290) but not everyone agrees it's a good idea — that's why it is optional — and it wouldn't fundamentally change anything for your scenario anyway.

**Comment by michaelklishin** [comment]
In this specific case a workaround could include [exposing `basic.consume`'s `nowait` flag](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/channel.rb#L859) which means there will be no `basic.consume-ok` sent by the server. It covers only one scenario, however, and will require non-trivial changes (#433).

I checked what channels do in the server: [RabbitMQ sends a basic.consume-ok immediately](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_channel.erl#L1434). However, `basic.consume` is delivered to the target queue master [concurrently](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_amqqueue.erl#L812) via a mechanism that can contact remote or local processes. Which can introduce the race condition.

The following should not into this issue as there will be only one outstanding continuation on each channel:

``` ruby
c = Bunny.new; c.start
ch = c.create_channel
ch2 = c.create_channel
q = ch.queue("abc", durable: true)
…
ch2.queue_declare(q.name, passive: true) => #<AMQ::Protocol::Queue::DeclareOk:0x007f8b3219dd58 @queue="abc", @message_count=0, @consumer_count=0>
```

**Comment by sullerandras** [comment]
Thanks @michaelklishin for the quick reply. Using a separate queue to get the `message_count` works:
```ruby
require 'bunny'

conn = Bunny.new
conn.start

channel = conn.create_channel
channel.prefetch 10 # need to set prefetch to get non 0 `message_count`
queue = channel.queue('testing_queue', exclusive: false, durable: false, auto_delete: false)

channel2 = conn.create_channel
queue2 = channel2.queue('testing_queue', passive: true)

queue.subscribe(manual_ack: true) do |deliver_info, metadata, payload|
  puts "======> received"
  puts "remaining messages: #{queue2.message_count}" # use the second queue here to avoid race condition
end
```
