### ISSUE TITLE
Consumer daemon that subscribes to a queue

### ISSUE THREAD

**Issue by pinkynrg** [ruby-amqp/bunny#516]
I'm trying to write a daemon method that allows me to subscribe to a queue and pop messages from there until I kill the daemon (otherwise I need it to run endlessly). 

```ruby
queue_host.subscribe(block:true) do |delivery_info, properties, body|
  #read poped messages
end
```

It seems like that when I get an Exception (for example Bunny::Session: got an exception when receiving data...) the execution of the code exists the subscription ruby block and my daemon ends.

 How should I handle this? Should I place everything in a while (true) loop with some Exception rescuing? I tried that and I didn't have much luck...

If someone can help me out it would be appreciated

**Comment by michaelklishin** [comment]
Please use the mailing list for questions as mentioned in `CONTRIBUTING.md`.

I cannot comment on an exception I haven't seen full stack trace for. The easiest way to keep a process around is

``` ruby
# without block: true
q.subscribe(…) do |…|
end

loop do
  sleep 1
end
```

or something like that. It can be done in a separate thread in case you cannot use the main one. 
There is an [Error Handling and Recovery guide](http://rubybunny.info/articles/error_handling.html) as well.

**Comment by pinkynrg** [comment]
Thanks man. I managed to solve! 

_Sent from my Motorola XT1585 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
