### ISSUE TITLE
exchange declarations don't check type of existing exchanges anymore

### ISSUE THREAD

**Issue by prettycoder** [ruby-amqp/bunny#517]
in this commit https://github.com/ruby-amqp/bunny/commit/8866f589049e84aaccd148895ef234d5ee526bbd
lines like:
```
Exchange.new(self, :fanout, name, opts)
```
were replaced with:
```
find_exchange(name) || Exchange.new(self, :fanout, name, opts)
```
but now for existing exchanges the type is not checked anymore and something like this is possible without getting Bunny::PreconditionFailed:
```
@exchange = @ch.topic("tv.ruby.error.1", :auto_delete => true)
@exchange = @ch.fanout("tv.ruby.error.1", :auto_delete => true)
```
(hope this explanation makes sense :) )

**Comment by michaelklishin** [comment]
Object caching has certain side effects. That change went into 2.7.0, so I don't find this a big deal. You can instantiate `Bunny::Exchange` yourself if needed or use `Bunny::Channel#exchange_declare` directly.

I wouldn't object to re-introducing the check but honestly, it would complicate the code with little gain. 
In some shape or form this will happen from time to time with the API we have (which the users generally like).

**Comment by michaelklishin** [comment]
Actually, I'm wrong: it was introduced in `2.6.5`. But the idea was to unify this behavior with that of queue declaration, so it's a "you win some, you lose some" kind of change :(

@prettycoder am I making sense?

**Comment by prettycoder** [comment]
Thanks Michael, 
yes, it makes sense. I had a test fail in a project I took over, so if this is the new behavior I'll change the test ;)
