### ISSUE TITLE
Publishing to missing exchange results in Timeout::Error upon closing the channel

### ISSUE THREAD

**Issue by stefansedich** [ruby-amqp/bunny#525]
When publishing to a missing exchange:

```ruby
channel = connection.create_channel
channel.basic_publish('', 'this-exchange-does-not-exist', {})
channel.close
```

I end up with a Timeout::Error upon closing the connection, is this the expected behavior? I would assume that this should work without issue as the basic_publish does not error and I can see the log correctly telling me that it is not a valid exchange without erroring however the subsequent close call is where it blows up.

```
/.gems/gems/bunny-2.6.6/lib/bunny/concurrent/continuation_queue.rb:39:in `block in poll': Timeout::Error (Timeout::Error)
	from /.gems/gems/bunny-2.6.6/lib/bunny/concurrent/continuation_queue.rb:30:in `synchronize'
	from /.gems/gems/bunny-2.6.6/lib/bunny/concurrent/continuation_queue.rb:30:in `poll'
	from /.gems/gems/bunny-2.6.6/lib/bunny/session.rb:1318:in `wait_on_continuations'
	from /.gems/gems/bunny-2.6.6/lib/bunny/session.rb:534:in `block in close_channel'
	from /usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /.gems/gems/bunny-2.6.6/lib/bunny/session.rb:530:in `close_channel'
	from /.gems/gems/bunny-2.6.6/lib/bunny/channel.rb:236:in `close'
	from shopify_collector_service.rb:11:in `<main>'
```

**Comment by michaelklishin** [comment]
Please direct your questions to the mailing list in the future.

Publishing to a non-existent exchange is a channel-level exception which closes the channel. Such exception notifications are entirely asynchronous, so if you try to close it before the channel finds out it is closed, there won't be a response (a connection-level error is the only reasonable outcome). Server logs should make it reasonably easy to see what was going on.
