### ISSUE TITLE
during graceful shutdown, the consumer will consume as many messages as possible which have been subscribed. 

### ISSUE THREAD

**Issue by HaoCHEN3** [ruby-amqp/bunny#532]
I am confused of graceful shutdown in consumer work pool. 
In my testing, if the queue originally has 60 messages. when one consumer starts, subscribe fn will immediately `fetch` all 60 messages from the queue (at this time. `rabbitmqctl list_queues` shows 0 messages in the queue). Meanwhile, gracefully shutdown shows pending because the work pool is terminating while dealing messages as it can before timeout. In my understanding (from the documents) as what I want, during graceful shutdown, the consumer only deals with the one current message instead of dealing with all messages. 

could anyone explain more details.

**Comment by michaelklishin** [comment]
Please use Bunny's mailing list for questions.

Consumer work pool tries to finish operations that were already started. It is entirely orthogonal to how many deliveries happen on a channel.

See [tutorial 2](https://www.rabbitmq.com/getstarted.html) and [documentation on confirms](http://www.rabbitmq.com/confirms.html). Bunny's own [guide on consumers](http://rubybunny.info/articles/queues.html) covers those topics as well.
