### ISSUE TITLE
Default CA store doesn't work

### ISSUE THREAD

**Issue by carlhoerberg** [ruby-amqp/bunny#539]
Looks like the default CA path is broken in Bunny 2.9.0

```
$ ruby -rbunny -e 'Bunny.new("amqps://user:pass@srv.rmq.cloudamqp.com").start'
E, [2018-01-10T14:22:42.423885 #30918] ERROR -- #<Bunny::Session:0x7ff9b596ee00 @84codes-prod-a.rmq.cloudamqp.com:5671, vhost=, addresses=[srv.rmq.cloudamqp.com:5671]>: No CA certificates found, add one with :tls_ca_certificates
W, [2018-01-10T14:22:42.424063 #30918]  WARN -- #<Bunny::Session:0x7ff9b596ee00 @84codes-prod-a.rmq.cloudamqp.com:5671, vhost=, addresses=[srv.rmq.cloudamqp.com:5671]>: Using TLS but no client certificate is provided! If RabbitMQ is configured to verify peer
certificate, connection upgrade will fail!

Traceback (most recent call last):
        3: from -e:1:in `<main>'
        2: from /Users/carl/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bunny-2.9.0/lib/bunny/session.rb:304:in `start'
        1: from /Users/carl/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bunny-2.9.0/lib/bunny/transport.rb:81:in `connect'
/Users/carl/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bunny-2.9.0/lib/bunny/transport.rb:81:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
```

Has worked very good up until now.

**Comment by michaelklishin** [comment]
Can you please do the same with debug logging?

I suspect it's a side effect of #534.

**Comment by carlhoerberg** [comment]
I think I found it here: https://github.com/ruby-amqp/bunny/pull/534/files#r160690153

**Comment by michaelklishin** [comment]
I suggest that we add more debug logging around CA certificate directories before working on a fix.

**Comment by carlhoerberg** [comment]
`Array(nil) => []` so `default_tls_certificates` will never be called

**Comment by michaelklishin** [comment]
@carlhoerberg good catch. Forcing the default if `tls_ca_certificates_paths_from` returns an empty list is what I'd do.

**Comment by michaelklishin** [comment]
Out in 2.9.1.

**Comment by bgeuken** [comment]
@michaelklishin Could you add an entry for this to the changelog? 
We just ran into this issue and it would have helped to have it there. Though we should have looked through the closed issues earlier. But that's a different story^^

**Comment by michaelklishin** [comment]
[It is for 2.9.x](https://github.com/ruby-amqp/bunny/blob/2.9.x-stable/ChangeLog.md#changes-between-bunny-290-and-291-jan-11th-2018).

**Comment by michaelklishin** [comment]
I will add a README section that links to release notes for the current/last 2-3 release series.

**Comment by bgeuken** [comment]
Oh, I see. I was only checking the readme of the master branch. And since there was a 2.9.0 tag but none for 2.9.1, I jumped to the wrong conclusion. I should have checked that branch as well^^

Thanks for clarifying, and for maintaining this gem:-) Very much appreciated!
