### ISSUE TITLE
Starting Rails Bunny worker at boot time

### ISSUE THREAD

**Issue by nadavb** [ruby-amqp/bunny#544]
Is there a recommended way to run the Bunny workers at boot time? (For example using Upstart, etc)

**Comment by michaelklishin** [comment]
Please post questions to the mailing list.

Bunny doesn't care how the Ruby process is started, whether Rails is used, how the process is monitored and so on.

Forking and concurrency considerations may be important on boot. There are two doc guides that cover those topics:

 * [Connecting to RabbitMQ](http://rubybunny.info/articles/connecting.html)
 * [Concurrency Considerations](http://rubybunny.info/articles/concurrency.html)
