### ISSUE TITLE
Channel#nack requeue option ignored

### ISSUE THREAD

**Issue by JulienAmoros** [ruby-amqp/bunny#545]
## Nack requeue option ignored

Hi everyone!
It seems like re-queuing on `Channel#nack` through `requeue: true` is ignored. 
`channel.nack(_delivery_info.delivery_tag, requeue: true)`
This doesn't seems to be proper behavior, do you have the same issue or did I miss anything?

 * I use docker container for RabbitMQ with management plugin
 * Bunny version: 2.9.2
 * Last RabbitMQ logs (not sure it's relevant though), obtained from `docker logs my-rabbit`
`2018-03-12 09:48:36.574 [info] <0.3238.0> accepting AMQP connection <0.3238.0> (172.17.0.1:57616 -> 172.17.0.2:5672)`
`2018-03-12 09:48:36.576 [info] <0.3238.0> connection <0.3238.0> (172.17.0.1:57616 -> 172.17.0.2:5672): user 'guest' authenticated and granted access to vhost '/'`
`2018-03-12 09:48:38.903 [info] <0.3250.0> accepting AMQP connection <0.3250.0> (172.17.0.1:57618 -> 172.17.0.2:5672)`
`2018-03-12 09:48:38.916 [info] <0.3250.0> connection <0.3250.0> (172.17.0.1:57618 -> 172.17.0.2:5672): user 'guest' authenticated and granted access to vhost '/'`
`2018-03-12 09:48:42.351 [info] <0.3264.0> accepting AMQP connection <0.3264.0> (172.17.0.1:57620 -> 172.17.0.2:5672)`
`2018-03-12 09:48:42.353 [info] <0.3264.0> connection <0.3264.0> (172.17.0.1:57620 -> 172.17.0.2:5672): user 'guest' authenticated and granted access to vhost '/'`
`2018-03-12 09:48:42.355 [info] <0.3264.0> closing AMQP connection <0.3264.0> (172.17.0.1:57620 -> 172.17.0.2:5672, vhost: '/', user: 'guest')`
`2018-03-12 09:48:46.117 [info] <0.3238.0> closing AMQP connection <0.3238.0> (172.17.0.1:57616 -> 172.17.0.2:5672, vhost: '/', user: 'guest')`
 * No Exception raised
 * Steps to reproduce or a failing test case:
1. Start RabbitMQ docker: `docker run -d --hostname my-rabbit --name some-rabbit -p 8080:15672 rabbitmq:3-management`
2. `ruby manual_nack_consumer.rb` (see below)
3. `ruby manual_ack_consumer.rb` (see below)
4. `ruby manual_producer.rb` (see below)

Code:
```ruby
# manual_producer.rb
require 'bunny'

connection = Bunny.new(hostname: '172.17.0.2')
connection.start
channel = connection.create_channel
queue = channel.queue('man_ack')

channel.default_exchange.publish('Hello World.....', routing_key: queue.name)
puts " [x] Sent 'Hello World!'"

connection.close


# manual_ack_consumer.rb
require 'bunny'

connection = Bunny.new(hostname:  '172.17.0.2')
connection.start
channel = connection.create_channel
channel.prefetch(1)
queue = channel.queue('man_ack')

begin
  puts ' [*] Waiting for messages. To exit press CTRL+C'
  queue.subscribe(block: true, manual_ack: true) do |_delivery_info, _properties, body|
    puts " [x] Processing #{body} (#{_delivery_info.delivery_tag})"
    sleep body.count('.')
    channel.ack(_delivery_info.delivery_tag)
    puts " [x] Processing over (#{_delivery_info.delivery_tag})"
  end
rescue Interrupt => _
  connection.close
  exit(0)
end


# manual_nack_consumer.rb
require 'bunny'

connection = Bunny.new(hostname:  '172.17.0.2')
connection.start
channel = connection.create_channel
channel.prefetch(1)
queue = channel.queue('man_ack')

begin
  puts ' [*] Waiting for messages. To exit press CTRL+C'
  queue.subscribe(block: true, manual_ack: true) do |_delivery_info, _properties, body|
    puts " [x] Processing #{body} (#{_delivery_info.delivery_tag})"
    channel.nack(_delivery_info.delivery_tag, requeue: true)
    puts 'Job failed'
  end
rescue Interrupt => _
  connection.close
  exit(0)
end
```

Side note: requeuing works properly to me when using `Channel#reject` with same arguments.

Regards :-)

**Comment by michaelklishin** [comment]
`Bunny::Channel#{reject,nack}` use positional arguments:

``` ruby
    # Rejects a message. A rejected message can be requeued or
    # dropped by RabbitMQ. This method is similar to {Bunny::Channel#reject} but
    # supports rejecting multiple messages at once, and is usually preferred.
    #
    # @param [Integer] delivery_tag Delivery tag to reject
    # @param [Boolean] multiple (false) Should all unacknowledged messages up to this be rejected as well?
    # @param [Boolean] requeue  (false) Should this message be requeued instead of dropping it?
    # @see Bunny::Channel#ack
    # @see http://rubybunny.info/articles/queues.html Queues and Consumers guide
    # @api public
    def nack(delivery_tag, multiple = false, requeue = false)
      basic_nack(delivery_tag.to_i, multiple, requeue)
    end
```

**Comment by michaelklishin** [comment]
I double checked and the [Consumers guide](http://rubybunny.info/articles/queues.html) uses positional arguments as well.

**Comment by michaelklishin** [comment]
Just in case: the reason why `reject` works in your example is simply because a map you're passing in evaluates to `true`. With `nack` it also does but that's the `multiple` parameter that ends up being set to `true`.

**Comment by JulienAmoros** [comment]
You're right, I didn't get that point at the moment, thanks for your answer!
