### ISSUE TITLE
Can't cancel message delivering for consumer

### ISSUE THREAD

**Issue by floodico** [ruby-amqp/bunny#547]
Hello there! I want to cancel my consumer. 
     
     subscription = task_queue.subscribe do |delivery_info, properties, payload|
       # do something
     end
     subscription.cancel # returns -  #<AMQ::Protocol::Basic::CancelOk:0x00007ffe3daf07d8 @consumer_tag="bunny-1522397906000-844518030111">

But after all my consumer still receives a message. Do i something wrong?

**Comment by michaelklishin** [comment]
Please use mailing list for questions.

**Comment by michaelklishin** [comment]
There is a natural race condition between a `basic.cancel` frame sent by the client and a stream of deliveries in flight sent by the broker. Plus every client implementation provides a buffer (queue as in data structures) of delivered but not yet processed messages. So you can get deliveries in flight or already buffered after a `basic.cancel` frame is sent. There won't be many of them but it can be e.g. the entire

Sending a `basic.cancel` before ack with [prefetch set to 1](http://www.rabbitmq.com/confirms.html) is the safest option but prefetch = 1 is also an [extremely conservative value](https://www.rabbitmq.com/blog/2014/04/14/finding-bottlenecks-with-rabbitmq-3-3/).

**Comment by michaelklishin** [comment]
[Mailing list thread](https://groups.google.com/forum/#!topic/ruby-amqp/2RJ8C6x0PUA).
