### ISSUE TITLE
Another uninitialized variable: @recovering_from_network_failure

### ISSUE THREAD

**Issue by hadmut** [ruby-amqp/bunny#585]
is like but #582 
/var/lib/gems/2.5.0/gems/bunny-2.14.3/lib/bunny/session.rb:720: warning: instance variable @recovering_from_network_failure not initialized

**Comment by hadmut** [comment]
And one more:

/var/lib/gems/2.5.0/gems/bunny-2.14.3/lib/bunny/session.rb:429: warning: instance variable @manually_closed not initialized

**Comment by michaelklishin** [comment]
I could not reproduce with Ripl but fair enough, should be addressed in `master` and  `2.14.x-stable`.
