### ISSUE TITLE
Custom hostname for TLS peer verification

### ISSUE THREAD

**Issue by kinnalru** [ruby-amqp/bunny#587]
Hi.

Bunny::Transport with TLS enabled using the same host for verification as which it connects: https://github.com/ruby-amqp/bunny/blob/10f8efc3035ed41a69707ba73fe7a09e1a6283ec/lib/bunny/transport.rb#L97

I our case we use static common name when generating RabbitMq certificate like `mq`, but often this is not resolvable hostname and we need t connect to bare IP in internal network.

So we need to be able to provide custom peer name to bunny for tls verification:
```ruby
bunny = Bunny.new({
   hostname: '172.22.22.22',
   tls: true,
   options[:tls_cert] ||= 'config/keys/cert.pem',
   options[:tls_key]  ||= 'config/keys/key.pem', 
   options[:tls_ca_certificates] ||= ['config/keys/cacert.pem'], # HERE "mq" in certificate attrs
   options[:verify_peer_name] = 'mq' # we need somthing like this
})
```

What you think about it?

**Comment by michaelklishin** [comment]
Please use the mailing list for questions in the future.

This is not a common scenario but then again, the whole SAN/CN comparison verification doesn't offer much protection anyway, only [peer certificate chain traversal](https://www.rabbitmq.com/ssl.html#peer-verification) does.

You can use [`Bunny::Session#configure_socket`](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L283) to configure any socket settings before `Bunny::Session#start` is used to initiate a connection.
