### ISSUE TITLE
Rubybunny is down

### ISSUE THREAD

**Issue by squeedee** [ruby-amqp/bunny#593]
Not sure if you're aware, but http://rubybunny.info/ is offline. Just wanted to ping you in case you hadn't noticed. 

Thanks!

**Comment by michaelklishin** [comment]
Thanks.

**Comment by michaelklishin** [comment]
There was a DNS provider "product renewal" mishap. I'm looking into it.

**Comment by michaelklishin** [comment]
Should be back up now, thanks for reporting.
