### ISSUE TITLE
Could you please provide example of callback impementation for confirm_select method?

### ISSUE THREAD

**Issue by Miroshni4enko** [ruby-amqp/bunny#596]

**Comment by michaelklishin** [comment]
I assume the question is not about [how to enable publisher confirms](https://github.com/ruby-amqp/bunny/blob/master/spec/higher_level_api/integration/publisher_confirms_spec.rb) but rather about using [streaming confirms](https://www.rabbitmq.com/publishers.html#data-safety) with Bunny. There is no way at the moment, the only option is the batch publishing one (see the aforementioned spec). See #432 as well.
