### ISSUE TITLE
Bunny raises asynchronous exceptions on the thread that opened the connection

### ISSUE THREAD

**Issue by bbascarevic-tti** [ruby-amqp/bunny#597]
Bunny is raising asynchronous exceptions using `Thread#raise` in the thread that happened to call `Session#start`. This introduces a potentially dangerous and unpredictable behavior as the asynchronous exception (interrupt) can happen at any point in the thread lifetime, even in an `ensure` section, and is effectively impossible to defend against. 

The proposal is to provide means to specify a `session_error_handler` object that implements `#raise`, which if specified would be used instead of the origin thread, otherwise it would fall back to origin thread for backwards compatibility.

https://github.com/bbascarevic-tti/bunny/commit/4b282030bece8ecbfd250c5d39f381640066c03c

**Comment by michaelklishin** [comment]
Sounds reasonable. Please submit a PR?

**Comment by bbascarevic-tti** [comment]
@michaelklishin Any estimates on when 2.16.0 might land on rubygems?

**Comment by michaelklishin** [comment]
[`2.16.1`](https://rubygems.org/gems/bunny/versions/2.16.1) is out. I had to yank `2.16.0` because I did not pull master before cutting it on this specific machine 🤦‍♂️ 🤦‍♀️
