### ISSUE TITLE
Support custom connection_name

### ISSUE THREAD

**Issue by brerx** [ruby-amqp/bunny#599]
Feature request:

rabbitmq-management has the ability to display a custom connection_name, if provided.

https://github.com/rabbitmq/rabbitmq-management/pull/172

As far as I can see, Bunny does not support this yet.

Can this be added, please?

**Comment by michaelklishin** [comment]
This is open source software, so you are welcome to contribute the features that you need.

[Client-provided connection name](https://www.rabbitmq.com/api-guide.html#client-provided-names) is transferred in a client property, `connection_name`, which can be set with Bunny. A more convenient helper, Java and .NET client-style, can be added as an option and then [merged together with other client-provided and default client properties](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L201).

**Comment by brerx** [comment]
Ok, thx for the hints. I will try to add it myself 👍

**Comment by michaelklishin** [comment]
So, something like this:

``` ruby
conn = Bunny.new(connection_name: "app XYZ #{rand}")
conn.start
```

which would be equivalent to

``` ruby
conn = Bunny.new(client_properties: {connection_name: "app XYZ #{rand}"})
conn.start
```

**Comment by hopewise** [comment]
@michaelklishin as this feature been released, we tried to use it but without luck

```
conn = Bunny.new(connection_name: "app XYZ #{rand}")
```


<img width="672" alt="Screenshot 2024-04-29 at 4 02 56 PM" src="https://github.com/ruby-amqp/bunny/assets/1061157/97c2a8b8-a642-4890-9ab6-43f40040d078">

**Comment by brerx** [comment]
Hm, we have been using this heavily ever since. Works like a charm. So in general, it's working. I can't spot the problem with your code, either...

**Comment by hopewise** [comment]
We use sneakers gem, it seems that it removes the connection name, the only way worked by setting it through sneakers gem its self https://github.com/jondot/sneakers/issues/410#issuecomment-780115384

**Comment by michaelklishin** [comment]
@brerx I have previously provided evidence that this feature does work as expected in https://github.com/rabbitmq/rabbitmq-server/discussions/11109.

Without an executable way to reproduce or even Bunny (or Sneakers) and RabbitMQ versions mentioned, I conclude that the reporter has zero respect towards open source software maintainers' time => I personally disengage.

If someone figures out why Sneakers overrides this field and presents a convincing argument why it should not, I can merge PRs for Sneakers (but sadly do not have the permissions to produce new releases).
