### ISSUE TITLE
huge memory leak when consumer pool can't handle the load

### ISSUE THREAD

**Issue by leksito** [ruby-amqp/bunny#603]
If the number of incoming messages is greater than the consumer is handling, the memory usage increases infinitely over time.
The simplest ruby ​​script can use a huge amount of memory
```
require 'bunny'

Process.setproctitle("test_consumer")

conn = Bunny.new(
# bunny conf
)
conn.start
channel = conn.create_channel

exchange = channel.send(:fanout, 'test')
queue = channel.queue('test_queue', exclusive: false)
queue.bind(exchange)

queue.subscribe do |*args|
  puts args.inspect[0..100]
  sleep 0.01 # mock message handling
end

Thread.list.reject { |t| t == Thread.current }.each(&:join)
```

![1](https://user-images.githubusercontent.com/13941862/101372386-e44a1700-38bc-11eb-9c82-acc2b5c96754.png)

and this memory is not released even after reducing the load

**Comment by leksito** [comment]
https://github.com/ruby-amqp/bunny/pull/604

**Comment by michaelklishin** [comment]
This is expected. Consumers should use manual acknowledgements with a [low enough prefetch value](https://www.rabbitmq.com/confirms.html) on their channels. This is the only fundamental solution.
