### ISSUE TITLE
losing published messages

### ISSUE THREAD

**Issue by padoauk** [ruby-amqp/bunny#611]
Hi.

Recently I've started RabbitMQ and bunny. With the following code, I tried simple but large pub/sub test and found some messages are lost. 

I've executed the script below, which should publish 100000 messages, iteratatively with 3 seconds pause. Then the number of messages subscriber receives fluctuates. The fluctuation looks like random, e.g. [99804, 99815, 99809, 99836, 99823, 99864, 99815, 99809, 999821] and so on.

When the sleep call, the comment line in the code below, is executed, the situation becomes pretty much better.

When tried with different publisher code written in python with pika and the same subscriber, there's no fluctuation and subscriber receives all the messages. Therefore, the problem exists in the ruby publisher.

Please let me know what is wrong ?

```
#!/usr/bin/env ruby

require 'bunny'

SrvIp = 'localhost'
Topic = 'my.topic'
NumID = 10000
NumIter = 10

# prepare messages of random byte array
def messages(num: 256, len: 256)
  msg = []
  num.times do
    msg.push( Random.bytes(len) )
  end

  return msg
end

Msgbuffer = messages(num: 256, len: 256)

# many routing keys
Route_names = []
NumID.times do |i|
  rname = "AA#{'%05d'%i}"
  Route_names.push(rname)
end

connection = Bunny.new(hostname: SrvIp)
connection.start
channel = connection.create_channel
exchange = channel.topic(Topic)

pt = 0
tm0 = Time.now
num = 0
NumIter.times do |i|
  Route_names.each do |nm|
    msg = Msgbuffer[pt % Msgbuffer.length]
    pt += 1
    begin
      exchange.publish(msg, routing_key: nm)
    rescue => e
      puts e.to_s
    end
    num += 1
    #sleep(0.000001)
  end
end
tm1 = Time.now

duration = tm1.to_f - tm0.to_f
puts "#messages: #{num}, duration: #{'%.2f' %(duration)} sec, avg: #{'%.2f' % (1000.0 * duration / num)} msg/msec"
```

Here's data of the environment:

RabbitMQ: (Docker container)
  OS: Linux
  RabbitMQ version: 3.8.15
  Node name: rabbit@rabbitmq
  Erlang configuration: Erlang/OTP 23 [erts-11.2.1] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1]

bunny:
  ruby: 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
  bunny (2.17.0)

**Comment by michaelklishin** [comment]
The code in this example does not use [publisher confirnms](https://www.rabbitmq.com/confirms.html#publisher-confirms). Data safety is a joint responsibility of RabbitMQ nodes and your own code. See [Publisher Data Safety](https://www.rabbitmq.com/publishers.html#data-safety).

**Comment by padoauk** [comment]
Thanks.
