### ISSUE TITLE
Gem includes test certificates

### ISSUE THREAD

**Issue by chaitrahegde115** [ruby-amqp/bunny#612]
Hi, 
 I have installed bunny-2.14.4 gem in td-agent. This gem has installed default certificates in spec/tls folder. So I wanted to know what is the use of these certificates and are these certificates really used in the runtime?
Also, if the certificates are not used at the runtime can these certificates be deleted while bundling the gem so that the default certificates are not bundled with bunny gem? Having default certificates bundled in a gem is a security risk.

**Comment by michaelklishin** [comment]
They are used by the test suite unless you override their location. They can be excluded. However, test files are included by default by RubyGems, so I am not sure if excluding tests is a common practice in the community.

**Comment by michaelklishin** [comment]
`spec/tls/*` and all files not under `lib` and `spec` have been excluded from the gem. I'll cut a new release after taking a look at one more issue.

**Comment by michaelklishin** [comment]
`2.18.0` is out.
