### ISSUE TITLE
Binding a queue to same exchange twice but using different routing keys not working as expected

### ISSUE THREAD

**Issue by andrecavallari** [ruby-amqp/bunny#616]
RabbitMQ version: 3.8.16 (Also tested with very latest version)
Bunny version: 2.18.0

When I try to bind the same queue on the same exchange but using different routing keys more than once, even if I always publish using same routing key it sends alternatively to both subscriptions, for example the code below:

```
require 'bunny'

bunny = Bunny.new('amqp://localhost:5672/app').tap(&:start)
channel = bunny.create_channel

exchange = channel.exchange('users.out', type: :topic)

channel.queue('app.in', durable: true).bind(exchange, routing_key: 'user.created').subscribe do |info, properties, body|
  puts "User created #{body}"
end

channel.queue('app.in', durable: true).bind(exchange, routing_key: 'user.updated').subscribe do |info, properties, body|
  puts "User updated #{body}"
end

exchange.publish('lorem@ipsum.com', routing_key: 'user.created')
exchange.publish('lorem@ipsum.com', routing_key: 'user.created')

begin
  sleep(5) while true
rescue Interrupt
  exit(0)  
end
```

Published twice to routing_key `user.created` but the output is:
```
User created lorem@ipsum.com
User updated lorem@ipsum.com
```

No matter how many messages I send to a specific routing key, always alternate when using same queue

**Comment by michaelklishin** [comment]
Your code has competing consumers on the same queue. The expected behavior with these QoS and acknowledgement settings is round robin, see tutorial 2 on rabbitmq.com. It has nothing to do with bindings or routing.
