### ISSUE TITLE
Heartbeat sender uses Time.now which is unreliable

### ISSUE THREAD

**Issue by blowfishpro** [ruby-amqp/bunny#676]
The Bunny heartbeat sender uses `Time.now` to track how long it's been since the last heartbeat (or other connection activity) and determine how long to wait before sending another heartbeat.

In one of our test suites, we discovered that the connection to the RabbitMQ server was unexpectedly closing due to missed heartbeats.  We discovered that this tends to happen with tests that [stub time](https://api.rubyonrails.org/classes/ActiveSupport/Testing/TimeHelpers.html).

So it seems like the heartbeat sender's accounting of when to send the next heartbeat is getting messed up by `Time.now` getting stubbed and jumping around.

It turns out there are other legitimate reasons not to use `Time.now` to measure elapsed time.  [This blog post](https://blog.dnsimple.com/2018/03/elapsed-time-with-ruby-the-right-way/) explains some of the details there.

The suggested alternative in that blog post is to use `Process.clock_gettime(Process::CLOCK_MONOTONIC)` (which returns a strictly increasing count of time since some arbitrary starting point, as a float number of second by default).  That seems to work well enough elsewhere, although one thing that's unclear to me is whether that's available on all of the platforms Bunny wants to support.

From a quick code search, `Bunny::Concurrent::ContinuationQueue` seems to also use `Time.now` to count elapsed time.  There are a couple of other cases where `Time.now` is used to generate pseudo-random consumer tags, although those have other components that will vary so they're unlikely to be an issue in practice.

As an aside, we're definitely wondering ourselves whether it's a good idea to stub time in higher level tests that actually interact with e.g. a real RabbitMQ server.  But that won't be trivial to address.

**Comment by michaelklishin** [comment]
According to [Ruby 2.5 docs](https://ruby-doc.org/core-2.5.1/Process.html), `Process.clock_gettime` with the monotonic time option is not something new.

I am all for changing all usages of `Time.now` to use the above version. We had/have to worry about this exact behavior on the RabbitMQ side, too.

**Comment by michaelklishin** [comment]
The difference between the values returned by `Process.clock_gettime(Process::CLOCK_MONOTONIC)` is apparently [the number of seconds](https://blog.dnsimple.com/2018/03/elapsed-time-with-ruby-the-right-way/):

``` ruby
t1 = Process.clock_gettime(Process::CLOCK_MONOTONIC); sleep 1; t2 = Process.clock_gettime(Process::CLOCK_MONOTONIC); t2 - t1
```

**Comment by blowfishpro** [comment]
Yes, although the 2nd argument can be used to adjust whether it returns float seconds, integer seconds, milliseconds, etc.  The zero point of the clock is arbitrary but it's designed to be consistent at least for the lifecycle of a process.

**Comment by michaelklishin** [comment]
@blowfishpro can you please give https://github.com/ruby-amqp/bunny/pull/677 a shot?

**Comment by blowfishpro** [comment]
Sorry we weren't able to look until now.  But we confirmed that this fix works.

**Comment by michaelklishin** [comment]
@blowfishpro no worries, I understand that late December is a very busy period for many :) Thank you for confirming, I will proceed to cut a new release in a bit.
