### ISSUE TITLE
Unsubscribe from queue

### ISSUE THREAD

**Issue by BrindleFly** [ruby-amqp/bunny#99]
I am looking to subscribe to receive a single message in a queue (a temporary queue that has an rpc response). Once I receive this message, I'd like to cancel the subscription.  Am I right there is no currently supported way to cancel a subscription? e.g.

```
  Timeout.timeout(15) do
      callback_queue.subscribe(:block=>true) do |delivery_info, properties, payload|
                   # Do work
                   # End blocking wait with unsubscribe
                   callback_queue.unsubscribe
      end
  end
```

**Comment by untoldone** [comment]
@michaelklishin what if you want to block? E.g. you want to block the thread until a specific message comes back. e.g.

```
consumer = binding.subscribe(manual_ack: true, block: true) do |delivery_info, properties, body|
  result = worker.call(body)
  @chan.ack(delivery_info.delivery_tag, false)
  consumer.cancel if result
end
```

Where `worker` can return true or false if it wants to cancel the consumer.

**Comment by untoldone** [comment]
Just solved it myself with something like this:

```
require "thread"

unblock = Queue.new # Ruby Queue, not Bunny::Queue
queue = channel.queue('').bind(@x, :routing_key => rk)
consumer = queue.subscribe do |delivery_info, properties, body|
  # do something
  result = determine_if_it_is_time_to_move_on
  unblock.enq true if result
end

unblock.deq # block until a message is enqueued in the ruby Queue
consumer.cancel
```

**Comment by michaelklishin** [comment]
@untoldone if you want to block you instantiate a `Bunny::Consumer` and use `Bunny::Channel#subscribe_with`, then use `Bunny::Consumer#cancel`.

**Comment by michaelklishin** [comment]
There is `Bunny::Concurrent` for cases when you need a basic concurrency primitive (e.g. a latch). No need to reinvent some things on top of `::Queue`.

**Comment by untoldone** [comment]
Thanks! I appreciate the followup.
